#!/usr/bin/env python3
"""pi05_libero on accelerator. Generated by the add-model skill — fill the TODO deltas.

The standard decoder loop is driven by the config `ops` block. Hand-edit ONLY:
  - VLM: implement compile_encoder() (vision is model-specific).
  - Any op the flags don't cover yet.
  - The padding obligations recorded in the manifest hw_notes (64-ALU / 128B rows).
"""
import builtins
import json
import math
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

import numpy as np

_original_print = builtins.print
_SILENT_MODE = False
def _quiet_print(*args, **kwargs):
    if not _SILENT_MODE:
        _original_print(*args, **kwargs)
builtins.print = _quiet_print

import torch

import user_dma_core
from user_dma_core import (
    DMA_DEVICE_H2C, DMA_DEVICE_C2H, TYPE, UE_VECTOR_SIZE, UE_ARGMAX_INDEX, UE_ARGMAX1_INDEX,
    URAM_NEAR_FULL_ELEMENTS, URAM_FULL_ELEMENTS,
    DRAM_INSTRUCTION_ADDR, INSTRUCTION_REG_REWRITE, MEMCPY_TYPE, INSTRUCTION_SIZE_BYTES,
    UnifiedEngine, ue_35bit_addr_shifter,
)
from nn_lib import (
    prefill_flash_attention_core,
    smart_bf16_permute_core,
    store_weight, store_quantized_weight, load_weight_cache, store_identity_matrix,
    eltwise_add_core_dram, eltwise_mul_core_dram,
    rms_norm_core_dram_post_add, layer_norm_core_dram_post_add,
)
from quant_lib import (
    quantize_q4_64 as _mlc_quantize_q4_64,
    quantize_fp4_64 as _mlc_quantize_fp4_64,
)


def _load_config(path=None):
    if path is None:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pi05_libero_config.json")
    with open(path) as f:
        return json.load(f)


_CFG = _load_config()
HF_MODEL_REPO = _CFG["paths"].get("hf_model_repo")
IS_VLM = True


def init_hang_prevention(ue):
    """5-step hardware clear. MUST stay identical to run_from_bin.py (see skill gotchas)."""
    halt = bytes(64)
    ue.dma_write(DMA_DEVICE_H2C, DRAM_INSTRUCTION_ADDR, halt, len(halt))
    print("[Init] HALT written to instruction DRAM base")


class Pi05Libero_UnifiedEngine(UnifiedEngine):
    _cfg = _CFG
    HIDDEN_SIZE       = _cfg["lm"]["hidden_size"]
    NUM_LAYERS        = _cfg["lm"]["num_layers"]
    NUM_HEADS         = _cfg["lm"]["num_heads"]
    NUM_KV_HEADS      = _cfg["lm"]["num_kv_heads"]
    GROUP_SIZE        = _cfg["lm"]["num_heads"] // _cfg["lm"]["num_kv_heads"]
    HEAD_DIM          = _cfg["lm"]["head_dim"]
    INTERMEDIATE_SIZE = _cfg["lm"]["intermediate_size"]
    VOCAB_SIZE        = _cfg["lm"]["vocab_size"]
    ROPE_THETA        = _cfg["lm"]["rope_theta"]
    RMS_NORM_EPS      = _cfg["lm"]["rms_norm_eps"]
    OPS               = _cfg["ops"]
    LM_QUANT          = _cfg["ops"]["lm_quant"]

    def __init__(self, script_dir=None, **kw):
        layout = self._cfg["dram_layout"]
        kw.setdefault("params_dram_base", int(layout["params_dram_base"], 16))
        kw.setdefault("tensor_dram_base", int(layout["tensor_dram_base"], 16))
        kw.setdefault("program_dram_base", int(layout["program_dram_base"], 16))
        super().__init__(**kw)
        self.script_dir = script_dir or os.path.dirname(os.path.abspath(__file__))

    # ---- weights -----------------------------------------------------------
    def weight_init(self):
        """Loads all weights to params DRAM. Vision-encoder weights are owned by a
        concurrently-edited helper (_weight_init_vision); LM prefix-stack weights
        (embedder + 18 Gemma layers) are owned by _weight_init_lm_prefix below."""
        if hasattr(self, "_weight_init_vision"):
            self._weight_init_vision()
        self._weight_init_lm_prefix()
        if hasattr(self, "weight_init_action_expert"):
            self.weight_init_action_expert()

    # -- Vision encoder weights (SigLIP So400m/14, 27 layers) ----------------
    def _weight_init_vision(self):
        """Loads the SigLIP vision-encoder weights (``PaliGemma.img.*``) from
        ``weights_export/*.npy`` into params DRAM.

        Quantization policy: every matmul weight matrix (patch-embed kernel, q/k/v/out
        projections, MLP Dense_0/Dense_1, head projection) -> IF4 (q4_64) via
        ``store_quantized_weight``. LayerNorm scale/bias, every bias, and the additive
        pos-embedding stay bf16 via ``store_weight``.

        The engine's quantized matmul (``matmat_mul_core`` with ``is_B_quantized=True``)
        computes ``A @ Bᵀ`` where B is stored **N×K** (out,in) row-major (see
        ``matmat_mul_core`` docstring) — the opposite of the JAX/Flax ``.kernel`` layout
        (K,N = in,out) used by this checkpoint, so every kernel is ``.T``-transposed
        before quantization.
        """
        wdir = os.path.join(self.script_dir, "weights_export")
        with open(os.path.join(wdir, "manifest.json")) as f:
            manifest = json.load(f)

        def _load(name):
            info = manifest[name]
            return torch.from_numpy(np.load(os.path.join(wdir, info["file"])))

        def _store_q4(mat_nk):
            """mat_nk: 2-D tensor already in N×K (out,in) layout."""
            packed, _ = _mlc_quantize_q4_64(mat_nk.to(torch.bfloat16).contiguous())
            return store_quantized_weight(self, packed)

        V = self._cfg["vision"]
        H  = V["hidden_size"]        # 1152
        NH = V["num_heads"]          # 16
        D  = V["head_dim"]           # 72
        DP = 128                     # padded head_dim for flash attention (72 -> 128)
        I  = V["intermediate_size"]  # 4304
        NP = V["num_patches"]        # 256
        PS = V["patch_size"]         # 14
        # matmat_mul_core_pbi's quantized-B path asserts K % UE_VECTOR_SIZE(64) == 0 (the scale
        # DRAM stride is linear in the K blocks). Patch-embed K=588 and the MLP inner dim
        # I=4304 are NOT 64-aligned, so pad both up to the next multiple of 64 with zeros
        # (extra input features / channels contribute exactly 0, so results are unaffected).
        PATCH_K = PS * PS * 3                                              # 588 (raw patch feature count)
        PK = ((PATCH_K + UE_VECTOR_SIZE - 1) // UE_VECTOR_SIZE) * UE_VECTOR_SIZE  # 640
        IP = ((I + UE_VECTOR_SIZE - 1) // UE_VECTOR_SIZE) * UE_VECTOR_SIZE        # 4352
        self.VIS_H, self.VIS_NH, self.VIS_D, self.VIS_DP = H, NH, D, DP
        self.VIS_I, self.VIS_I_PAD, self.VIS_S, self.VIS_PATCH_K = I, IP, NP, PK
        # The flash kernel applies an internal 1/sqrt(head_dim_pad) scale; pre-scale Q by
        # sqrt(head_dim_pad/head_dim) so the *effective* scale is the correct 1/sqrt(head_dim)
        # (proven pattern, see project_vision_attn_headdim_pad_unpad memory). Folded into the
        # Q weight/bias here so no extra runtime broadcast-mul is needed.
        q_scale = math.sqrt(DP / D)

        # --- patch embedding (K padded 588 -> 640; caller must zero-pad the patchified
        # pixel input to width PK too, see _tensor_init_vision) ---
        k = _load("PaliGemma.img.embedding.kernel").reshape(-1, H)          # [588, 1152] (K,N)
        b = _load("PaliGemma.img.embedding.bias")                          # [1152]
        k_pad = torch.zeros(PK, H, dtype=k.dtype)
        k_pad[:PATCH_K] = k
        self.vis_embed_scale, self.vis_embed_data = _store_q4(k_pad.T)     # -> [1152, 640] (N,K)
        self.vis_embed_bias = store_weight(self, b)
        self.vis_pos_embed = store_weight(self, _load("PaliGemma.img.pos_embedding").reshape(NP, H))

        pfx = "PaliGemma.img.Transformer.encoderblock"
        ln0_w, ln0_b = _load(f"{pfx}.LayerNorm_0.scale"), _load(f"{pfx}.LayerNorm_0.bias")
        ln1_w, ln1_b = _load(f"{pfx}.LayerNorm_1.scale"), _load(f"{pfx}.LayerNorm_1.bias")
        q_k, q_b = _load(f"{pfx}.MultiHeadDotProductAttention_0.query.kernel"), _load(f"{pfx}.MultiHeadDotProductAttention_0.query.bias")
        k_k, k_b = _load(f"{pfx}.MultiHeadDotProductAttention_0.key.kernel"), _load(f"{pfx}.MultiHeadDotProductAttention_0.key.bias")
        v_k, v_b = _load(f"{pfx}.MultiHeadDotProductAttention_0.value.kernel"), _load(f"{pfx}.MultiHeadDotProductAttention_0.value.bias")
        o_k, o_b = _load(f"{pfx}.MultiHeadDotProductAttention_0.out.kernel"), _load(f"{pfx}.MultiHeadDotProductAttention_0.out.bias")
        d0_k, d0_b = _load(f"{pfx}.MlpBlock_0.Dense_0.kernel"), _load(f"{pfx}.MlpBlock_0.Dense_0.bias")
        d1_k, d1_b = _load(f"{pfx}.MlpBlock_0.Dense_1.kernel"), _load(f"{pfx}.MlpBlock_0.Dense_1.bias")

        self.vis_layer_addrs = []
        for l in range(27):
            la = {}
            la['ln0_w'] = store_weight(self, ln0_w[l])
            la['ln0_b'] = store_weight(self, ln0_b[l])
            la['ln1_w'] = store_weight(self, ln1_w[l])
            la['ln1_b'] = store_weight(self, ln1_b[l])

            # Q/K/V projections: pad each head's OUTPUT block D->DP (72->128) with zero
            # columns/bias, concatenated per head (col h*DP:h*DP+D real, h*DP+D:h*DP+DP
            # zero) -- the proven qwen2.5_vl_3b "qk_padded/v_padded" pattern. This keeps
            # every per-head DMA stride a full DP*bpe=256B (AXI-beat aligned) instead of
            # D*bpe=144B (NOT a multiple of the 32B AXI beat), and needs no separate
            # real-vs-padded strided copy at attention time.
            def _pad_proj(k_l, b_l, scale=1.0):
                k2d = k_l.reshape(H, NH, D)                    # (K, heads, D)
                k_pad = torch.zeros(H, NH, DP, dtype=k2d.dtype)
                k_pad[:, :, :D] = k2d * scale
                b_pad = torch.zeros(NH, DP, dtype=b_l.dtype)
                b_pad[:, :D] = b_l * scale
                return k_pad.reshape(H, NH * DP).T, b_pad.reshape(NH * DP)  # (N,K), (N)

            qk, qb = _pad_proj(q_k[l], q_b[l], q_scale)
            la['q_scale'], la['q_data'] = _store_q4(qk)
            la['q_bias'] = store_weight(self, qb)

            for short, kk_l, kb_l in (('k', k_k[l], k_b[l]), ('v', v_k[l], v_b[l])):
                kk, kb = _pad_proj(kk_l, kb_l)
                la[f'{short}_scale'], la[f'{short}_data'] = _store_q4(kk)
                la[f'{short}_bias'] = store_weight(self, kb)

            # Out projection: pad each head's INPUT block D->DP (zero rows) to match the
            # padded-concatenated attention-output layout (padded columns are exactly 0 on
            # both sides, so the extra zero rows contribute nothing either way).
            o3d = o_k[l].reshape(NH, D, H)                      # (heads, D, out)
            o_pad = torch.zeros(NH, DP, H, dtype=o3d.dtype)
            o_pad[:, :D, :] = o3d
            ok = o_pad.reshape(NH * DP, H).T                    # (N=H, K=NH*DP)
            la['o_scale'], la['o_data'] = _store_q4(ok)
            la['o_bias'] = store_weight(self, o_b[l])

            # fc1 (Dense_0): pad OUTPUT width I->IP with zero columns/bias so fc1's own
            # output buffer is directly IP-wide (real values in [0:I], exact zeros in
            # [I:IP] since both weight and bias are zero there) — no separate scatter needed.
            d0k_pad = torch.zeros(H, IP, dtype=d0_k.dtype)
            d0k_pad[:, :I] = d0_k[l]
            d0b_pad = torch.zeros(IP, dtype=d0_b.dtype)
            d0b_pad[:I] = d0_b[l]
            la['fc1_scale'], la['fc1_data'] = _store_q4(d0k_pad.T)          # [4352,1152] (N,K)
            la['fc1_bias'] = store_weight(self, d0b_pad)

            # fc2 (Dense_1): pad INPUT (K) I->IP with zero rows (fc1's padded zero columns
            # contribute exactly 0 through these zero weight rows).
            d1k_pad = torch.zeros(IP, H, dtype=d1_k.dtype)
            d1k_pad[:I] = d1_k[l]
            la['fc2_scale'], la['fc2_data'] = _store_q4(d1k_pad.T)          # [1152,4352] (N,K)
            la['fc2_bias'] = store_weight(self, d1_b[l])

            self.vis_layer_addrs.append(la)

        self.vis_encoder_norm_w = store_weight(self, _load("PaliGemma.img.Transformer.encoder_norm.scale"))
        self.vis_encoder_norm_b = store_weight(self, _load("PaliGemma.img.Transformer.encoder_norm.bias"))

        hk = _load("PaliGemma.img.head.kernel")   # [1152, 2048] (K,N)
        hb = _load("PaliGemma.img.head.bias")
        self.VIS_HEAD_OUT = hk.shape[1]
        self.vis_head_scale, self.vis_head_data = _store_q4(hk.T)          # [2048,1152] (N,K)
        self.vis_head_bias = store_weight(self, hb)

        print(f"_weight_init_vision done; params DRAM usage: {self.get_params_dram_usage()} bytes")

    # -- LM prefix stack weights (Gemma-2B: embedder + 18 layers) ------------
    def _npy(self, name):
        """Load one exported weight array (float32) from weights_export/<name>.npy."""
        path = os.path.join(self.script_dir, "weights_export", f"{name}.npy")
        return torch.from_numpy(np.load(path).astype(np.float32))

    def _quant_store(self, w2d):
        """w2d: (out, in) float32 -> quantize_q4_64 -> store_quantized_weight. in-dim must be %64==0."""
        w2d = w2d.to(torch.bfloat16).contiguous()
        packed, _ = _mlc_quantize_q4_64(w2d)
        return store_quantized_weight(self, packed)

    def _weight_init_lm_prefix(self):
        """Loads the Gemma-2B prefix LM stack: token embedder (host-side gather table,
        kept resident as bf16 for use at compile_prefix time) + per-layer RMSNorm
        (bf16, unquantized) + attn/mlp matmul weights (IF4 q4_64, per quant policy)."""
        H, D, I = self.HIDDEN_SIZE, self.HEAD_DIM, self.INTERMEDIATE_SIZE
        NH, NKV = self.NUM_HEADS, self.NUM_KV_HEADS

        # Embedder: kept as a host-resident bf16 lookup table (gather, not a matmul) —
        # rows are indexed directly at compile_prefix() time, no DRAM matmul weight needed.
        self.embedding_table = self._npy("PaliGemma.llm.embedder.input_embedding").to(torch.bfloat16)

        q_all = self._npy("PaliGemma.llm.layers.attn.q_einsum.w")          # (18, 8, 2048, 256)
        kv_all = self._npy("PaliGemma.llm.layers.attn.kv_einsum.w")        # (18, 2, 1, 2048, 256)
        o_all = self._npy("PaliGemma.llm.layers.attn.attn_vec_einsum.w")   # (18, 8, 256, 2048)
        ln1_all = self._npy("PaliGemma.llm.layers.pre_attention_norm.scale")  # (18, 2048)
        ln2_all = self._npy("PaliGemma.llm.layers.pre_ffw_norm.scale")        # (18, 2048)
        gate_up_all = self._npy("PaliGemma.llm.layers.mlp.gating_einsum")     # (18, 2, 2048, 16384)
        down_all = self._npy("PaliGemma.llm.layers.mlp.linear")               # (18, 16384, 2048)

        self.lm_layer_addrs = []
        for l in range(self.NUM_LAYERS):
            la = {}
            la["ln1"] = store_weight(self, ln1_all[l])
            la["ln2"] = store_weight(self, ln2_all[l])

            # q_einsum[l]: (heads, d_in=2048, head_dim=256) each head is (in,out) -> transpose
            # to (out,in) per head, stack heads along N (out) axis -> (heads*head_dim, d_in).
            q_heads = [q_all[l, h].transpose(0, 1) for h in range(NH)]       # each (256, 2048)
            q_2d = torch.cat(q_heads, dim=0)                                  # (2048, 2048) = (N,K)
            la["q_scale"], la["q_data"] = self._quant_store(q_2d)

            k_2d = kv_all[l, 0, 0].transpose(0, 1)   # (head_dim, d_in) = (256, 2048)
            v_2d = kv_all[l, 1, 0].transpose(0, 1)
            la["k_scale"], la["k_data"] = self._quant_store(k_2d)
            la["v_scale"], la["v_data"] = self._quant_store(v_2d)

            # attn_vec_einsum[l]: (heads, head_dim, d_out) -> merge (heads,head_dim) as
            # the K (in) axis, matching the (seq, heads*head_dim) attn-output layout,
            # transpose to (out, in).
            o_2d = o_all[l].reshape(NH * D, H).transpose(0, 1)   # (2048, 2048) = (N=d_out, K=heads*hd)
            la["o_scale"], la["o_data"] = self._quant_store(o_2d)

            gate_2d = gate_up_all[l, 0].transpose(0, 1)   # (2048,16384) in,out -> (16384,2048)
            up_2d = gate_up_all[l, 1].transpose(0, 1)
            la["gate_scale"], la["gate_data"] = self._quant_store(gate_2d)
            la["up_scale"], la["up_data"] = self._quant_store(up_2d)

            # down_proj K=16384 exceeds URAM row capacity for a single matmat_mul_core
            # call (see compile_prefix's K-split note) -> store as two (2048,8192)
            # K-half blobs, matmul'd separately and eltwise-added back together.
            down_2d = down_all[l].transpose(0, 1)   # (16384,2048) in,out -> (2048,16384)
            FF_HALF = down_2d.shape[1] // 2
            la["down_lo_scale"], la["down_lo_data"] = self._quant_store(down_2d[:, :FF_HALF].contiguous())
            la["down_hi_scale"], la["down_hi_data"] = self._quant_store(down_2d[:, FF_HALF:].contiguous())

            self.lm_layer_addrs.append(la)
        print(f"_weight_init_lm_prefix: {self.NUM_LAYERS} layers loaded")

    # ---- tensors -----------------------------------------------------------
    def tensor_init(self, max_seq_len=512):
        """Allocate activation/KV buffers. Addresses chosen by allocate_tensor_dram.
        NOTE: every buffer's innermost dim must be a multiple of 64 (pad if not)."""
        bpe = 2
        S, H, I, D = max_seq_len, self.HIDDEN_SIZE, self.INTERMEDIATE_SIZE, self.HEAD_DIM
        KV = self.NUM_KV_HEADS * D
        self.KV_HEAD_STRIDE = S * D * bpe
        self.KV_LAYER_STRIDE = self.NUM_KV_HEADS * self.KV_HEAD_STRIDE
        kv_total = self.NUM_LAYERS * self.KV_LAYER_STRIDE
        self.LAYER0_K_DRAM = self.allocate_tensor_dram(kv_total)
        self.LAYER0_V_DRAM = self.allocate_tensor_dram(kv_total)
        self.LAYER0_INPUT_DRAM    = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_PRE_NORM_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_Q_DRAM        = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_K_PROJ_DRAM   = self.allocate_tensor_dram(S * KV * bpe)
        self.LAYER0_V_PROJ_DRAM   = self.allocate_tensor_dram(S * KV * bpe)
        self.LAYER0_Q_PERM_DRAM   = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_ATTN_OUT_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_ATTN_SCRATCH_DRAM = self.allocate_tensor_dram((D * S + max(D, 64) * S) * bpe)
        self.LAYER0_ATTN_RESULT_DRAM  = self.allocate_tensor_dram(S * H * bpe)
        # Shared-subroutine flash attention (mirrors compile_encoder's vision
        # pattern): the flash body is compiled ONCE and jumped to from every
        # (layer, head) call site instead of being statically re-emitted 18x
        # (one full seq_len=1024 attention body per layer was the actual root
        # cause of compile_prefix hanging for hours -- prefill_flash_attention_core
        # has no PBI/runtime-loop mode at all, only flash_attention_core does).
        # K/V need no per-head marshalling (MQA: same buffer for every head,
        # already fixed at LAYER0_K_PROJ_DRAM/LAYER0_V_PROJ_DRAM); only Q needs
        # copying into this fixed scratch slot before each jump, and OUTPUT
        # needs copying out after each return.
        self.LAYER0_FLASH_Q_DRAM = self.allocate_tensor_dram(S * D * bpe)
        self.LAYER0_FLASH_OUT_DRAM = self.allocate_tensor_dram(S * D * bpe)
        self.LAYER0_FLASH_ATTN_P_DRAM = self.allocate_tensor_dram(S * S * bpe)
        self.LAYER0_O_PROJ_DRAM   = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_MLP_GATE_DRAM = self.allocate_tensor_dram(S * I * bpe)
        self.LAYER0_MLP_UP_DRAM   = self.allocate_tensor_dram(S * I * bpe)
        self.LAYER0_MLP_MULT_DRAM = self.allocate_tensor_dram(S * I * bpe)
        self.LAYER0_MLP_DOWN_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.FINAL_NORM_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.LOGITS_DRAM     = self.allocate_tensor_dram(self.VOCAB_SIZE * bpe)
        if IS_VLM:
            # NOT in params.bin — must be re-allocated here (see skill gotchas).
            # store_identity_matrix always produces a fixed UE_VECTOR_SIZE(64)x64 identity;
            # it is reused as-is by the flash kernel regardless of head_dim/head_dim_pad.
            self.identity_addr = store_identity_matrix(self)
            self._tensor_init_vision()
        print(f"tensor_init done; tensor DRAM at 0x{self.get_tensor_dram_addr():X}")

    def _tensor_init_vision(self):
        """Allocate vision-encoder activation/scratch DRAM. Appended at the END of
        tensor_init (after all LM buffers) so no earlier LM buffer address shifts
        (run_from_bin.py must mirror this ordering — see skill gotchas)."""
        bpe = 2
        H, NH, D, DP, I, IP, S = (self.VIS_H, self.VIS_NH, self.VIS_D, self.VIS_DP,
                                   self.VIS_I, self.VIS_I_PAD, self.VIS_S)
        PK = self.VIS_PATCH_K   # 640 (588 padded to a multiple of 64), patch-embed matmul K
        HO = self.VIS_HEAD_OUT  # 2048, head projection output width

        # Patchified pixel input (host pre-patchifies raw pixels into [S, 588], mirroring the
        # torch reference's unfold+reshape, zero-padded to width PK=640 — no on-device
        # patchify is compiled here). Zero the whole buffer once so the pad columns
        # [588:640] the host never writes stay exactly 0 (matches the zero-padded kernel).
        self.VIS_PIXEL_IN_DRAM   = self.allocate_tensor_dram(S * PK * bpe)
        self.dma_write(DMA_DEVICE_H2C, self.VIS_PIXEL_IN_DRAM,
                        torch.zeros(S * PK, dtype=torch.bfloat16), S * PK * bpe)
        self.VIS_PATCH_PROJ_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_IO_A_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_IO_B_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_LN_OUT_DRAM = self.allocate_tensor_dram(S * H * bpe)
        # Q/K/V/attn-result are per-head-padded (D->DP=128, see _weight_init_vision's
        # _pad_proj) so every per-head DMA stride is AXI-beat aligned.
        HP = NH * DP
        self.VIS_Q_DRAM = self.allocate_tensor_dram(S * HP * bpe)
        self.VIS_K_DRAM = self.allocate_tensor_dram(S * HP * bpe)
        self.VIS_V_DRAM = self.allocate_tensor_dram(S * HP * bpe)
        self.VIS_ATTN_RESULT_DRAM = self.allocate_tensor_dram(S * HP * bpe)
        self.VIS_O_PROJ_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_RESIDUAL_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_MLP_INTER_DRAM = self.allocate_tensor_dram(S * IP * bpe)  # padded I->IP (see fc1/fc2)
        self.VIS_MLP_OUT_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_POST_LN_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.VIS_HEAD_OUT_DRAM = self.allocate_tensor_dram(S * HO * bpe)

        # LN zeros-replay buffer, shared by every LN call (see layer_norm_core_dram_pbi).
        self.vis_zeros_addr = self.allocate_tensor_dram(max(H, I) * bpe)
        self.dma_write(DMA_DEVICE_H2C, self.vis_zeros_addr,
                        torch.zeros(max(H, I), dtype=torch.bfloat16), max(H, I) * bpe)

        # §7 shared-subroutine per-head attention (proven smolvlm2/qwen2.5vl pattern): one
        # flash body reused across all (layer, head) call sites via strided-DMA head
        # marshalling. Buffers are padded to DP=128 (head_dim 72 -> 128, see hw_notes/
        # project_vision_attn_headdim_pad_unpad); only the real 72 columns are ever written
        # by the per-head gather/scatter, so the padded tail columns stay zero forever once
        # zero-initialized here — K's padded lanes dot to 0 and V's padded lanes contribute
        # 0 to the weighted sum, so attention math is unaffected and no explicit unpad
        # selection-matrix step is needed (the padding is self-annihilating by construction).
        self.VIS_FLASH_Q_DRAM = self.allocate_tensor_dram(S * DP * bpe)
        self.VIS_FLASH_K_DRAM = self.allocate_tensor_dram(S * DP * bpe)
        self.VIS_FLASH_V_DRAM = self.allocate_tensor_dram(S * DP * bpe)
        self.VIS_FLASH_OUT_DRAM = self.allocate_tensor_dram(S * DP * bpe)
        self.VIS_FLASH_ATTN_P_DRAM = self.allocate_tensor_dram(S * S * bpe)
        self.VIS_ATTN_SCRATCH_DRAM = self.allocate_tensor_dram((DP * S + DP * S) * bpe)
        zeros_dp = torch.zeros(S * DP, dtype=torch.bfloat16)
        for addr in (self.VIS_FLASH_Q_DRAM, self.VIS_FLASH_K_DRAM, self.VIS_FLASH_V_DRAM):
            self.dma_write(DMA_DEVICE_H2C, addr, zeros_dp, S * DP * bpe)
        print(f"    _tensor_init_vision done; tensor DRAM at 0x{self.get_tensor_dram_addr():X}")

    # ---- matmul dispatch ---------------------------------------------------
    def _matmul(self, M, K, N, A, proj, la, OUT, **kw):
        """Dispatch a (M,K)@(N,K)^T matmul against per-layer weight dict `la`, keyed by
        `proj` (e.g. 'q', 'k', 'v', 'o', 'gate', 'up', 'down'). All LM prefix weights are
        IF4 q4_64 per quant policy."""
        assert self.LM_QUANT == "q4_64", f"unsupported LM_QUANT={self.LM_QUANT}"
        return self.matmat_mul_core(
            M=M, K=K, N=N, A_DRAM_ADDR=A, B_DRAM_ADDR=la[f"{proj}_data"],
            OUTPUT_DRAM_ADDR=OUT, is_B_quantized=True, data_type=TYPE.IF4,
            SCALE_DRAM_ADDR=la[f"{proj}_scale"], **kw)

    def _dram_copy(self, size_bytes, src, dst):
        """DRAM->DRAM copy via a SRAM roundtrip, chunked through URAM_A. Used to
        stage per-layer K/V projections into the persistent KV-cache region."""
        bpe = 2
        elems = size_bytes // bpe
        chunk = min(URAM_NEAR_FULL_ELEMENTS, elems)
        sram = 0x00000
        for start, take in self.chunk_ranges(elems, chunk):
            off = start * bpe
            self.accelerator_memory_to_sram(src + off, sram, take)
            self.sram_to_accelerator_memory(sram, dst + off, take)

    def _dram_split_copy(self, rows, row_elems, col_offset, col_take, src, dst):
        """Extract a column slice [col_offset : col_offset+col_take) from a (rows,
        row_elems) row-major DRAM buffer into its own tightly-packed (rows, col_take)
        DRAM buffer, via a strided SRAM roundtrip. Used to materialize contiguous
        K-halves of the MLP intermediate (S, I) buffer for the down-proj K-split
        (matmat_mul_core_legacy cannot chunk K=16384 in one call; see compile_prefix)."""
        bpe = 2
        row_chunk = max(1, URAM_NEAR_FULL_ELEMENTS // col_take)
        sram = 0x00000
        for start, take in self.chunk_ranges(rows, row_chunk):
            self.accelerator_memory_to_sram(
                src + (start * row_elems + col_offset) * bpe, sram, take * col_take,
                stride_bytes_per_chunk=col_take * bpe, stride_jump_bytes=row_elems * bpe)
            self.sram_to_accelerator_memory(sram, dst + start * col_take * bpe, take * col_take)

    # ---- prefix LM stack (Gemma-2B, ported from pi05_torch_ref.prefix_forward /
    # joint_attention's `pre_tokens is not None` branch) ---------------------
    def build_prefix_attn_bias(self, seq_len, valid_len):
        """Bidirectional additive bias (seq_len, seq_len) bf16: 0 everywhere prefix
        tokens attend to each other; -1e36 on any column >= valid_len (padded lanes),
        matching pi05_torch_ref.build_prefix_attn_bias's placeholder (all-unmasked
        among real tokens, padding excluded). Not float('-inf') -- avoids NaN from
        exp(-inf - -inf) in the softmax kernel."""
        NEG = -1e36
        bias = torch.zeros((seq_len, seq_len), dtype=torch.bfloat16)
        if valid_len < seq_len:
            bias[:, valid_len:] = NEG
        return bias

    def embed_and_concat_prefix(self, token_ids, vision_embeddings=None, seq_len=1024):
        """Text-embedding lookup (host-side gather from self.embedding_table) concatenated
        with vision tokens (already-projected (n_vis, hidden) bf16, e.g. from
        compile_encoder's output), padded to seq_len. Writes the result to
        LAYER0_INPUT_DRAM. Returns valid_len (vision + text, before padding)."""
        H = self.HIDDEN_SIZE
        vis = vision_embeddings if vision_embeddings is not None else torch.zeros((0, H), dtype=torch.bfloat16)
        n_vis = vis.shape[0]

        tid = torch.tensor(token_ids, dtype=torch.long)
        text_embed = self.embedding_table[tid].to(torch.bfloat16)   # (n_text, H) host-side gather

        valid_len = n_vis + text_embed.shape[0]
        assert valid_len <= seq_len, f"prefix valid_len={valid_len} exceeds seq_len={seq_len}"

        full = torch.zeros((seq_len, H), dtype=torch.bfloat16)
        full[:n_vis] = vis
        full[n_vis:valid_len] = text_embed
        self.dma_to_accelerator_memory(self.LAYER0_INPUT_DRAM, full)
        return valid_len

    def compile_prefix(self, seq_len, valid_len=None):
        """18-layer Gemma-2B prefix stack: RMSNorm -> MQA flash-attn (bidirectional
        bias) -> residual -> RMSNorm -> gated-SiLU MLP -> residual. Per-layer K/V
        projections are staged into the persistent LAYER0_K_DRAM/LAYER0_V_DRAM cache
        (see tensor_init's KV_LAYER_STRIDE/KV_HEAD_STRIDE) for later reuse by the
        action-expert suffix stack (out of scope here).

        Ports pi05_torch_ref.prefix_forward + joint_attention's `pre_tokens is not
        None` branch. suf_tokens branch is out of scope."""
        S, H, I, D = seq_len, self.HIDDEN_SIZE, self.INTERMEDIATE_SIZE, self.HEAD_DIM
        NH, NKV, KV = self.NUM_HEADS, self.NUM_KV_HEADS, self.NUM_KV_HEADS * self.HEAD_DIM
        assert NKV == 1, "compile_prefix assumes pure MQA (num_kv_heads=1); broadcast via num_q_heads"
        bpe = 2

        valid_len = valid_len if valid_len is not None else S
        self.prefix_bias_dram = store_weight(self, self.build_prefix_attn_bias(S, valid_len))

        bpe = 2
        FF_HALF = I // 2
        self.LAYER0_MLP_DOWN_LO_IN_DRAM = self.allocate_tensor_dram(S * FF_HALF * bpe)
        self.LAYER0_MLP_DOWN_HI_IN_DRAM = self.allocate_tensor_dram(S * FF_HALF * bpe)
        self.LAYER0_MLP_DOWN_LO_OUT_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.LAYER0_MLP_DOWN_HI_OUT_DRAM = self.allocate_tensor_dram(S * H * bpe)

        # PBI dynamic-M loop (mirrors compile_encoder's vis_S_reg): without this,
        # every matmul/RMSNorm below compiles a fully-unrolled static instruction
        # stream per M=1024 row-chunk, which for 18 layers blew the compiled
        # program up to ~684MB (vs. vision's 745KB for 27 layers) and triggered a
        # DMA transfer-size failure. gpr_M_reg makes the outer row loop a runtime
        # trip count instead of static unrolling.
        prefix_S_reg = self.alloc_isa_reg()
        self.generate_instruction_add_set(prefix_S_reg, S)

        # Shared-subroutine flash attention (see tensor_init's LAYER0_FLASH_*
        # buffers): the flash body is compiled ONCE after the main per-layer loop
        # ends (below a HALT) and jumped to from every (layer, head) call site,
        # exactly like compile_encoder's vis_sub_start pattern. prefill_flash_
        # attention_core (the non-PBI all-heads-at-once convenience wrapper) has
        # no runtime-loop mode and was statically re-emitting a full seq_len=1024
        # attention body per layer -- 18 of those never finished compiling.
        prefix_prog_base = self.get_program_dram_addr()
        prefix_gpr_bucket = self.alloc_isa_reg()
        prefix_gpr_ret = self.alloc_isa_reg()
        prefix_call_sites: list[int] = []
        prefix_num_buckets = S // UE_VECTOR_SIZE

        for layer_idx in range(self.NUM_LAYERS):
            la = self.lm_layer_addrs[layer_idx]
            h_in = self.LAYER0_INPUT_DRAM if layer_idx == 0 else self.LAYER0_MLP_DOWN_DRAM

            # 1. pre-attention RMSNorm
            self.rms_norm_core_dram(M=S, N=H, A_DRAM_ADDR=h_in,
                                     OUTPUT_DRAM_ADDR=self.LAYER0_PRE_NORM_DRAM, GAMMA_DRAM_ADDR=la["ln1"],
                                     gpr_M_reg=prefix_S_reg)

            # 2. Q/K/V projections (MQA: K/V project to a single head_dim, not NH*D)
            self._matmul(M=S, K=H, N=H, A=self.LAYER0_PRE_NORM_DRAM, proj="q", la=la, OUT=self.LAYER0_Q_DRAM, gpr_M_reg=prefix_S_reg)
            self._matmul(M=S, K=H, N=KV, A=self.LAYER0_PRE_NORM_DRAM, proj="k", la=la, OUT=self.LAYER0_K_PROJ_DRAM, gpr_M_reg=prefix_S_reg)
            self._matmul(M=S, K=H, N=KV, A=self.LAYER0_PRE_NORM_DRAM, proj="v", la=la, OUT=self.LAYER0_V_PROJ_DRAM, gpr_M_reg=prefix_S_reg)

            # 3. permute Q from (seq, heads, head_dim) -> (heads, seq, head_dim); K/V
            # already (seq, head_dim) since num_kv_heads=1 == the layout
            # prefill_flash_attention_core expects for a single KV head.
            smart_bf16_permute_core(self, (S, NH, D), [1, 0, 2],
                                     self.LAYER0_Q_DRAM, self.LAYER0_Q_PERM_DRAM)

            # 4. stage this layer's K/V into the persistent KV cache for downstream reuse.
            k_cache_addr = self.LAYER0_K_DRAM + layer_idx * self.KV_LAYER_STRIDE
            v_cache_addr = self.LAYER0_V_DRAM + layer_idx * self.KV_LAYER_STRIDE
            self._dram_copy(S * KV * bpe, self.LAYER0_K_PROJ_DRAM, k_cache_addr)
            self._dram_copy(S * KV * bpe, self.LAYER0_V_PROJ_DRAM, v_cache_addr)

            # 5. MQA flash attention, bidirectional bias (no causal flag), per head
            # via the shared subroutine: Q for this head is copied (contiguous,
            # already separated by the step-3 permute) into the fixed
            # LAYER0_FLASH_Q_DRAM scratch, then jump into the one compiled flash
            # body, then the (fixed-address) output is copied into this head's
            # slot of LAYER0_ATTN_OUT_DRAM. K/V need no marshalling -- MQA means
            # the same LAYER0_K_PROJ_DRAM/LAYER0_V_PROJ_DRAM buffer (already
            # current for this layer, see step 2) is valid for every head, and
            # the subroutine's K/V addresses are fixed to those same buffers.
            head_bytes = S * D * bpe
            for h in range(NH):
                self._dram_copy(head_bytes, self.LAYER0_Q_PERM_DRAM + h * head_bytes, self.LAYER0_FLASH_Q_DRAM)
                self.generate_instruction_add_set(prefix_gpr_bucket, prefix_num_buckets)
                self.pad_capture_to_64b_boundary()
                return_word_addr = ue_35bit_addr_shifter(
                    prefix_prog_base + (self.capture_count + 2) * INSTRUCTION_SIZE_BYTES)
                self.generate_instruction_add_set(prefix_gpr_ret, return_word_addr)
                prefix_call_sites.append(self.capture_count)
                self.generate_instruction_jump_abs(target_instruction_word_addr=0)
                self._dram_copy(head_bytes, self.LAYER0_FLASH_OUT_DRAM, self.LAYER0_ATTN_OUT_DRAM + h * head_bytes)

            # 6. permute attn output (heads, seq, head_dim) -> (seq, heads*head_dim)
            smart_bf16_permute_core(self, (NH, S, D), [1, 0, 2],
                                     self.LAYER0_ATTN_OUT_DRAM, self.LAYER0_ATTN_RESULT_DRAM)

            # 7. output projection + residual
            self._matmul(M=S, K=H, N=H, A=self.LAYER0_ATTN_RESULT_DRAM, proj="o", la=la, OUT=self.LAYER0_O_PROJ_DRAM, gpr_M_reg=prefix_S_reg)
            eltwise_add_core_dram(self, S * H, h_in, self.LAYER0_O_PROJ_DRAM, self.LAYER0_O_PROJ_DRAM)

            # 8. pre-FFW RMSNorm
            self.rms_norm_core_dram(M=S, N=H, A_DRAM_ADDR=self.LAYER0_O_PROJ_DRAM,
                                     OUTPUT_DRAM_ADDR=self.LAYER0_PRE_NORM_DRAM, GAMMA_DRAM_ADDR=la["ln2"],
                                     gpr_M_reg=prefix_S_reg)

            # 9. gated-SiLU MLP + residual
            self._matmul(M=S, K=H, N=I, A=self.LAYER0_PRE_NORM_DRAM, proj="gate", la=la,
                         OUT=self.LAYER0_MLP_GATE_DRAM, silu_enable=True, gpr_M_reg=prefix_S_reg)
            self._matmul(M=S, K=H, N=I, A=self.LAYER0_PRE_NORM_DRAM, proj="up", la=la, OUT=self.LAYER0_MLP_UP_DRAM, gpr_M_reg=prefix_S_reg)
            eltwise_mul_core_dram(self, S * I, self.LAYER0_MLP_GATE_DRAM, self.LAYER0_MLP_UP_DRAM, self.LAYER0_MLP_MULT_DRAM)
            # down_proj K=16384: matmat_mul_core_legacy can't fit a full K=16384 row in
            # URAM in one call, so split into two K=8192 halves (materialized as
            # contiguous buffers) and eltwise-add the partial results (parakeet's
            # FF-down-proj K-split pattern).
            FF_HALF = I // 2
            self._dram_split_copy(S, I, 0, FF_HALF, self.LAYER0_MLP_MULT_DRAM, self.LAYER0_MLP_DOWN_LO_IN_DRAM)
            self._dram_split_copy(S, I, FF_HALF, FF_HALF, self.LAYER0_MLP_MULT_DRAM, self.LAYER0_MLP_DOWN_HI_IN_DRAM)
            self._matmul(M=S, K=FF_HALF, N=H, A=self.LAYER0_MLP_DOWN_LO_IN_DRAM, proj="down_lo", la=la, OUT=self.LAYER0_MLP_DOWN_LO_OUT_DRAM, gpr_M_reg=prefix_S_reg)
            self._matmul(M=S, K=FF_HALF, N=H, A=self.LAYER0_MLP_DOWN_HI_IN_DRAM, proj="down_hi", la=la, OUT=self.LAYER0_MLP_DOWN_HI_OUT_DRAM, gpr_M_reg=prefix_S_reg)
            eltwise_add_core_dram(self, S * H, self.LAYER0_MLP_DOWN_LO_OUT_DRAM, self.LAYER0_MLP_DOWN_HI_OUT_DRAM, self.LAYER0_MLP_DOWN_DRAM)
            eltwise_add_core_dram(self, S * H, self.LAYER0_O_PROJ_DRAM, self.LAYER0_MLP_DOWN_DRAM, self.LAYER0_MLP_DOWN_DRAM)

        # Main per-layer program ends here; the shared flash-attention subroutine
        # (jumped to from every per-head call site above) is compiled once below,
        # exactly like compile_encoder's vis_sub_start pattern.
        self.generate_instruction_halt()

        prefix_sub_start, _prefix_flops = self.flash_attention_core(
            head_dim=D, seq_len=S,
            Q_DRAM_ADDR=self.LAYER0_FLASH_Q_DRAM, K_DRAM_ADDR=self.LAYER0_K_PROJ_DRAM,
            V_DRAM_ADDR=self.LAYER0_V_PROJ_DRAM, OUTPUT_DRAM_ADDR=self.LAYER0_FLASH_OUT_DRAM,
            SCRATCH_DRAM_ADDR=self.LAYER0_ATTN_SCRATCH_DRAM, ATTN_P_DRAM_ADDR=self.LAYER0_FLASH_ATTN_P_DRAM,
            IDENTITY_DRAM_ADDR=self.identity_addr, BIAS_DRAM_ADDR=self.prefix_bias_dram,
            gpr_bucket_idx=prefix_gpr_bucket, num_buckets=prefix_num_buckets, gpr_ret_id=prefix_gpr_ret)
        for _idx in prefix_call_sites:
            self._patch_jump_immediate(_idx, ue_35bit_addr_shifter(prefix_sub_start))

        self.release_isa_reg()  # prefix_gpr_ret
        self.release_isa_reg()  # prefix_gpr_bucket
        self.release_isa_reg()  # prefix_S_reg
        print(f"compile_prefix: {self.NUM_LAYERS} layers compiled, seq_len={S}, valid_len={valid_len}")

        # ---- BUGFIX (interface reconciliation): the action-expert stack
        # (compile_suffix_step / tensor_init_action_expert) expects
        # self.PREFIX_SEQ_LEN + self.prefix_k_cache_addr[l]/prefix_v_cache_addr[l]
        # per-layer DRAM addresses. The real per-layer K/V cache was staged above
        # into LAYER0_K_DRAM/LAYER0_V_DRAM + layer_idx*KV_LAYER_STRIDE (each layer's
        # slice already has shape (S, KV)=(S, NUM_KV_HEADS*HEAD_DIM)=(S, HEAD_DIM)
        # since NUM_KV_HEADS==1 -- exactly the (PREFIX_SEQ_LEN, HEAD_DIM) shape the
        # action-expert code expects). Point the expected attrs directly at those
        # real addresses so tensor_init_action_expert's placeholder fallback never
        # triggers.
        self.PREFIX_SEQ_LEN = S
        self.prefix_k_cache_addr = [self.LAYER0_K_DRAM + l * self.KV_LAYER_STRIDE for l in range(self.NUM_LAYERS)]
        self.prefix_v_cache_addr = [self.LAYER0_V_DRAM + l * self.KV_LAYER_STRIDE for l in range(self.NUM_LAYERS)]

        return self.LAYER0_MLP_DOWN_DRAM

    # ---- prefill -----------------------------------------------------------
    def compile_prefill(self, seq_len):
        """Standard decoder loop driven by self.OPS. Fill _matmul/weight_init first.
        Confirm the prefill PBI mode matches the current branch."""
        S, H, I, D = seq_len, self.HIDDEN_SIZE, self.INTERMEDIATE_SIZE, self.HEAD_DIM
        for layer_idx in range(self.NUM_LAYERS):
            la = self.lm_layer_addrs[layer_idx]
            h_in = self.LAYER0_INPUT_DRAM if layer_idx == 0 else self.LAYER0_MLP_DOWN_DRAM
            # 1. input norm (fused post-add for layers 1+)
            # 2. q/k/v proj   3. rope   4. attn (GQA, causal)   5. o proj
            # 6. post-attn norm   7. mlp (gated_silu/gelu)
            # See references/op-library.md for the exact call order + flags.
            raise NotImplementedError("wire the op chain from references/op-library.md")

    # ---- decode ------------------------------------------------------------
    def compile_decode(self):
        """Single-token decode loop. Confirm the decode PBI mode matches the branch."""
        raise NotImplementedError("wire the decode op chain")

    # ---- VLM hook ----------------------------------------------------------
    def compile_encoder(self):
        """Compile the 27-layer SigLIP So400m/14 vision encoder (bidirectional, no RoPE,
        no causal mask — see hw_notes). Structure follows the proven smolvlm2_test.py §7
        shared-subroutine-flash pattern: PBI row loops for matmul/layer_norm/eltwise
        (gpr_M_reg), one flash body shared across every (layer, head) call site via
        strided-DMA head marshalling, head_dim padded 72->128 for the flash kernel (see
        _tensor_init_vision for why no explicit unpad selection-matrix is needed). All
        matmul weights are IF4 q4_64 (quant policy) -> quantized_matmul dispatch.
        """
        from user_dma_core import TYPE
        S, H, NH, D, DP, IP = (self.VIS_S, self.VIS_H, self.VIS_NH, self.VIS_D, self.VIS_DP,
                                self.VIS_I_PAD)
        bpe = 2

        # layer_norm_core_dram_pbi chunking (replicated so we prime n_chunks correctly).
        _ln_ops_per_row = 6
        _ln_chunk = min(URAM_NEAR_FULL_ELEMENTS // H, S, (256 - 4) // _ln_ops_per_row)
        while S % _ln_chunk != 0:
            _ln_chunk -= 1
        ln_n_chunks = S // _ln_chunk

        self.start_capture()

        vis_S_reg = self.alloc_isa_reg()
        vis_ln_chunks = self.alloc_isa_reg()
        self.generate_instruction_add_set(vis_S_reg, S)
        self.generate_instruction_add_set(vis_ln_chunks, ln_n_chunks)

        def vis_matmul(M, K, N, A, la, proj, OUT, bias=None, **kw):
            self.matmat_mul_core(M=M, K=K, N=N, A_DRAM_ADDR=A, B_DRAM_ADDR=la[f'{proj}_data'],
                OUTPUT_DRAM_ADDR=OUT, is_B_quantized=True, data_type=TYPE.IF4,
                SCALE_DRAM_ADDR=la[f'{proj}_scale'], C_DRAM_ADDR=bias, bias_mode="broadcast_N",
                gpr_M_reg=vis_S_reg, **kw)

        # === Patch embedding: patchified pixels [S, 588] -> [S, 1152] (+ pos_embedding) ===
        vis_matmul(S, self.VIS_PATCH_K, H, self.VIS_PIXEL_IN_DRAM,
            {'embed_data': self.vis_embed_data, 'embed_scale': self.vis_embed_scale}, 'embed',
            self.VIS_PATCH_PROJ_DRAM, bias=self.vis_embed_bias)
        eltwise_add_core_dram(self, size=S * H, A_DRAM_ADDR=self.VIS_PATCH_PROJ_DRAM,
            B_DRAM_ADDR=self.vis_pos_embed, OUTPUT_DRAM_ADDR=self.VIS_IO_A_DRAM)

        # §7 shared-subroutine attention: the per-head flash body is compiled ONCE after the
        # encoder HALT; every per-(layer,head) call site marshals its head's [S, D] Q/K/V
        # (padded to [S, DP]) into the fixed VIS_FLASH buffers and jumps in.
        vis_prog_base = self.get_program_dram_addr()
        vis_gpr_bucket = self.alloc_isa_reg()
        vis_gpr_ret = self.alloc_isa_reg()
        vis_call_sites: list[int] = []
        vis_num_buckets = S // UE_VECTOR_SIZE

        for layer_idx, la in enumerate(self.vis_layer_addrs):
            h_in  = self.VIS_IO_A_DRAM if layer_idx % 2 == 0 else self.VIS_IO_B_DRAM
            h_out = self.VIS_IO_B_DRAM if layer_idx % 2 == 0 else self.VIS_IO_A_DRAM
            # LN0 (PBI)
            self.layer_norm_core_dram(M=S, N=H, A_DRAM_ADDR=h_in, OUTPUT_DRAM_ADDR=self.VIS_LN_OUT_DRAM,
                GAMMA_DRAM_ADDR=la['ln0_w'], BETA_DRAM_ADDR=la['ln0_b'], gpr_M_reg=vis_ln_chunks,
                ZEROS_DRAM_ADDR=self.vis_zeros_addr)
            # Q/K/V projections (PBI, IF4). N=NH*DP: weights are pre-padded per-head
            # D->DP=128 (see _weight_init_vision's _pad_proj) so the buffers below are
            # already head-block-aligned at DP=128, no separate real/padded copy needed.
            HP = NH * DP
            for proj, dst in [('q', self.VIS_Q_DRAM), ('k', self.VIS_K_DRAM), ('v', self.VIS_V_DRAM)]:
                vis_matmul(S, H, HP, self.VIS_LN_OUT_DRAM, la, proj, dst, bias=la[f'{proj}_bias'])
            # Per-head bidirectional flash attention (no mask, no RoPE). Each head's block is
            # a full DP=128-wide (256B) column slice -> every DMA stride below is AXI-beat
            # (32B) aligned, unlike a bare D=72 (144B) slice.
            elems = S * DP
            col_stride = DP * bpe   # one head's column block width (aligned)
            row_jump = HP * bpe     # full [S, HP] row stride
            for h in range(NH):
                col = h * col_stride
                for src, dst in ((self.VIS_Q_DRAM + col, self.VIS_FLASH_Q_DRAM),
                                 (self.VIS_K_DRAM + col, self.VIS_FLASH_K_DRAM),
                                 (self.VIS_V_DRAM + col, self.VIS_FLASH_V_DRAM)):
                    self.accelerator_memory_to_sram(src, 0x00000, elems,
                        stride_bytes_per_chunk=col_stride, stride_jump_bytes=row_jump)
                    self.sram_to_accelerator_memory(0x00000, dst, elems)
                self.generate_instruction_add_set(vis_gpr_bucket, S // UE_VECTOR_SIZE)
                self.pad_capture_to_64b_boundary()
                return_word_addr = ue_35bit_addr_shifter(
                    vis_prog_base + (self.capture_count + 2) * INSTRUCTION_SIZE_BYTES)
                self.generate_instruction_add_set(vis_gpr_ret, return_word_addr)
                vis_call_sites.append(self.capture_count)
                self.generate_instruction_jump_abs(target_instruction_word_addr=0)
                self.accelerator_memory_to_sram(self.VIS_FLASH_OUT_DRAM, 0x00000, elems)
                self.sram_to_accelerator_memory(0x00000, self.VIS_ATTN_RESULT_DRAM + col, elems,
                    stride_bytes_per_chunk=col_stride, stride_jump_bytes=row_jump)
            # O projection + residual + LN1 (PBI)
            vis_matmul(S, HP, H, self.VIS_ATTN_RESULT_DRAM, la, 'o', self.VIS_O_PROJ_DRAM, bias=la['o_bias'])
            eltwise_add_core_dram(self, size=S * H, A_DRAM_ADDR=h_in, B_DRAM_ADDR=self.VIS_O_PROJ_DRAM,
                OUTPUT_DRAM_ADDR=self.VIS_RESIDUAL_DRAM)
            self.layer_norm_core_dram(M=S, N=H, A_DRAM_ADDR=self.VIS_RESIDUAL_DRAM, OUTPUT_DRAM_ADDR=self.VIS_LN_OUT_DRAM,
                GAMMA_DRAM_ADDR=la['ln1_w'], BETA_DRAM_ADDR=la['ln1_b'], gpr_M_reg=vis_ln_chunks,
                ZEROS_DRAM_ADDR=self.vis_zeros_addr)
            # MLP: Dense_0 + GELU (sigmoid-approx — the engine's only hardware GELU; the
            # reference uses tanh-approx GELU, a small documented numeric deviation),
            # Dense_1, residual.
            vis_matmul(S, H, IP, self.VIS_LN_OUT_DRAM, la, 'fc1', self.VIS_MLP_INTER_DRAM,
                bias=la['fc1_bias'], gelu_enable=True)
            vis_matmul(S, IP, H, self.VIS_MLP_INTER_DRAM, la, 'fc2', self.VIS_MLP_OUT_DRAM, bias=la['fc2_bias'])
            eltwise_add_core_dram(self, size=S * H,
                A_DRAM_ADDR=self.VIS_RESIDUAL_DRAM, B_DRAM_ADDR=self.VIS_MLP_OUT_DRAM, OUTPUT_DRAM_ADDR=h_out)

        # Final encoder_norm (PBI) + head projection (IF4).
        final_vis = self.VIS_IO_A_DRAM if len(self.vis_layer_addrs) % 2 == 0 else self.VIS_IO_B_DRAM
        self.layer_norm_core_dram(M=S, N=H, A_DRAM_ADDR=final_vis, OUTPUT_DRAM_ADDR=self.VIS_POST_LN_DRAM,
            GAMMA_DRAM_ADDR=self.vis_encoder_norm_w, BETA_DRAM_ADDR=self.vis_encoder_norm_b,
            gpr_M_reg=vis_ln_chunks, ZEROS_DRAM_ADDR=self.vis_zeros_addr)
        vis_matmul(S, H, self.VIS_HEAD_OUT, self.VIS_POST_LN_DRAM,
            {'head_data': self.vis_head_data, 'head_scale': self.vis_head_scale}, 'head',
            self.VIS_HEAD_OUT_DRAM, bias=self.vis_head_bias)

        self.generate_instruction_halt()   # encoder ends; shared flash body follows.

        vis_sub_start, _vis_flops = self.flash_attention_core(head_dim=DP, seq_len=S,
            Q_DRAM_ADDR=self.VIS_FLASH_Q_DRAM, K_DRAM_ADDR=self.VIS_FLASH_K_DRAM,
            V_DRAM_ADDR=self.VIS_FLASH_V_DRAM, OUTPUT_DRAM_ADDR=self.VIS_FLASH_OUT_DRAM,
            SCRATCH_DRAM_ADDR=self.VIS_ATTN_SCRATCH_DRAM, ATTN_P_DRAM_ADDR=self.VIS_FLASH_ATTN_P_DRAM,
            IDENTITY_DRAM_ADDR=self.identity_addr,
            gpr_bucket_idx=vis_gpr_bucket, num_buckets=vis_num_buckets, gpr_ret_id=vis_gpr_ret)
        for _idx in vis_call_sites:
            self._patch_jump_immediate(_idx, ue_35bit_addr_shifter(vis_sub_start))

        self.release_isa_reg()  # vis_gpr_ret
        self.release_isa_reg()  # vis_gpr_bucket
        self.release_isa_reg()  # vis_ln_chunks
        self.release_isa_reg()  # vis_S_reg
        self.stop_capture()

        all_bytes = bytearray()
        for inst in self.capture_buffer:
            all_bytes.extend(inst.get_bytes())
        program_addr = self.get_program_dram_addr()
        self._dma_write_retry(DMA_DEVICE_H2C, program_addr, all_bytes, len(all_bytes))
        self.allocate_program_dram(len(all_bytes))
        self.clear_capture_buffer()
        self._vis_program_addr = program_addr
        print(f"    Vision encoder compiled: {len(all_bytes)} bytes at 0x{program_addr:X}")
        return program_addr

    # =========================================================================
    # Action-expert (Gemma-300M) flow-matching denoising stack.
    #
    # Ported from pi05_torch_ref.py: ada_rms_norm / gated_mlp / sincos_pos_embed /
    # joint_attention(suf_tokens branch) / suffix_step / the Euler loop in run_pi05.
    #
    # Geometry (manifest hw_notes): 18 layers, hidden=1024, heads=8, kv_heads=1,
    # head_dim=256 (== self.HEAD_DIM, shared with the prefix Gemma-2B geometry --
    # self.identity_addr from tensor_init() is already sized for this head_dim).
    # intermediate=4096. All multiples of 64: no padding needed on those dims.
    #
    # ASSUMED PREFIX KV-CACHE INTERFACE (not finalized by the prefix agent at the
    # time this was written -- reconcile before running end-to-end):
    #   self.PREFIX_SEQ_LEN            -- int, padded prefix token count (manifest: 1024)
    #   self.prefix_k_cache_addr[l]    -- DRAM base for layer l's cached K, shape
    #                                      (PREFIX_SEQ_LEN, HEAD_DIM) bf16, kv_heads=1 (MQA)
    #   self.prefix_v_cache_addr[l]    -- same for V
    # If those attributes are missing, tensor_init_action_expert() below allocates
    # a zero-filled placeholder buffer per layer so compile still runs; real prefix
    # KV must be DMA'd into that placeholder (or the attrs pointed at the prefix
    # agent's real buffers) before this is numerically correct.
    # =========================================================================
    AE_HIDDEN = 1024
    AE_INTERMEDIATE = 4096
    AE_LAYERS = 18
    AE_HEADS = 8
    AE_KV_HEADS = 1
    AE_ACTION_DIM_PADDED = 32
    AE_ACTION_HORIZON = 10
    AE_ACTION_HORIZON_PADDED = 64  # padded for 64-alignment (flash / matmul row tiling)
    AE_NUM_DENOISE_STEPS = 10

    # ---- action-expert weights ---------------------------------------------
    def weight_init_action_expert(self):
        """Load action-expert (Gemma-300M) weights from weights_export/*.npy into
        params DRAM. Additive to weight_init(): hooked in via the hasattr() check
        in weight_init() above, does not touch the prefix/vision weight loading
        owned by the other two agents.

        Quantization policy: all matmul weight matrices (action_in_proj,
        time_mlp_in/out, action_out_proj, q/kv/attn_vec einsum, mlp gating/linear,
        and the AdaRMSNorm conditioning Dense_0 kernels) are IF4 (q4_64) via
        quantize_q4_64 + store_quantized_weight. Biases and norm terms stay bf16
        via store_weight. AdaRMSNorm itself has no learned gamma (plain RMSNorm);
        only its conditioning Dense layer has a kernel+bias.

        Weight layout note: weights_export tensors are JAX-style (in_features,
        out_features) i.e. consumed as ``x @ W``. The engine's matmat_mul_core
        computes ``A @ B^T`` with B stored (N, K) = (out, in). Every matmul
        weight is therefore transposed (last two dims) before quantizing/storing.
        """
        wdir = os.path.join(self.script_dir, "weights_export")
        manifest_path = os.path.join(wdir, "manifest.json")
        with open(manifest_path) as f:
            wman = json.load(f)

        def _load(name):
            info = wman[name]
            arr = np.load(os.path.join(wdir, info["file"]))
            return torch.from_numpy(arr.astype(np.float32))

        def _store_matmul(name):
            """Load (..., K, N) JAX-layout weight, transpose last two dims ->
            (..., N, K), quantize to IF4, store. Returns (scale_addr, data_addr)."""
            w = _load(name).transpose(-1, -2).contiguous().to(torch.bfloat16)
            data, _ = _mlc_quantize_q4_64(w)
            return store_quantized_weight(self, data.tobytes())

        def _store_bf16(name):
            return store_weight(self, _load(name).to(torch.bfloat16))

        def _store_matmul_kpad(name, k_pad):
            """Like _store_matmul, but zero-pads the K (reduction) dim up to
            k_pad. Needed for action_in_proj: real action_dim=32 < the
            engine's matmat_mul_core K%64==0 requirement (also the IF4
            block_size=64 boundary)."""
            w = _load(name).transpose(-1, -2).contiguous()  # (N, K_real)
            k_real = w.shape[-1]
            if k_real < k_pad:
                w = torch.nn.functional.pad(w, (0, k_pad - k_real))
            w = w.to(torch.bfloat16)
            data, _ = _mlc_quantize_q4_64(w)
            return store_quantized_weight(self, data.tobytes())

        # --- flow-matching I/O projections + timestep MLP (not per-layer) ---
        # action_in_proj: K=action_dim=32 padded to 64 (matmat_mul_core requires
        # K % UE_VECTOR_SIZE(64) == 0); the caller (compile_denoise_loop) zero-pads
        # AE_XT_DRAM into AE_XT_PAD_DRAM (S, 64) to match.
        self.ae_action_in_scale, self.ae_action_in_data = _store_matmul_kpad("action_in_proj.kernel", 64)
        self.ae_action_in_bias = _store_bf16("action_in_proj.bias")
        self.ae_time_in_scale, self.ae_time_in_data = _store_matmul("time_mlp_in.kernel")
        self.ae_time_in_bias = _store_bf16("time_mlp_in.bias")
        self.ae_time_out_scale, self.ae_time_out_data = _store_matmul("time_mlp_out.kernel")
        self.ae_time_out_bias = _store_bf16("time_mlp_out.bias")
        self.ae_action_out_scale, self.ae_action_out_data = _store_matmul("action_out_proj.kernel")
        self.ae_action_out_bias = _store_bf16("action_out_proj.bias")

        # --- per-layer action-expert transformer weights ---------------------
        self.ae_layer_addrs = []
        for layer in range(self.AE_LAYERS):
            la = {}

            def _store_matmul_layer(name, sl):
                w = _load(name)[sl].transpose(-1, -2).contiguous().to(torch.bfloat16)
                data, _ = _mlc_quantize_q4_64(w)
                return store_quantized_weight(self, data.tobytes())

            # AdaRMSNorm conditioning: Dense_0 (1024 -> 3*1024=3072), kernel quantized,
            # bias stays bf16.
            la["pre_attn_norm_dense_scale"], la["pre_attn_norm_dense_data"] = \
                _store_matmul_layer("PaliGemma.llm.layers.pre_attention_norm_1.Dense_0.kernel", layer)
            la["pre_attn_norm_dense_bias"] = store_weight(
                self, _load("PaliGemma.llm.layers.pre_attention_norm_1.Dense_0.bias")[layer].to(torch.bfloat16))
            la["pre_ffw_norm_dense_scale"], la["pre_ffw_norm_dense_data"] = \
                _store_matmul_layer("PaliGemma.llm.layers.pre_ffw_norm_1.Dense_0.kernel", layer)
            la["pre_ffw_norm_dense_bias"] = store_weight(
                self, _load("PaliGemma.llm.layers.pre_ffw_norm_1.Dense_0.bias")[layer].to(torch.bfloat16))

            # Attention: per-head Q (8, 1024, 256), shared single-head KV (1, 1024, 256), O (8, 256, 1024)
            q_all = _load("PaliGemma.llm.layers.attn.q_einsum_1.w")[layer]     # (8, 1024, 256)
            kv_all = _load("PaliGemma.llm.layers.attn.kv_einsum_1.w")[layer]   # (2, 1, 1024, 256)
            o_all = _load("PaliGemma.llm.layers.attn.attn_vec_einsum_1.w")[layer]  # (8, 256, 1024)
            la["q_scale"], la["q_data"] = [], []
            la["o_scale"], la["o_data"] = [], []
            for h in range(self.AE_HEADS):
                qw = q_all[h].transpose(-1, -2).contiguous().to(torch.bfloat16)  # (256,1024) N,K
                data, _ = _mlc_quantize_q4_64(qw)
                sa, da = store_quantized_weight(self, data.tobytes())
                la["q_scale"].append(sa); la["q_data"].append(da)
                ow = o_all[h].transpose(-1, -2).contiguous().to(torch.bfloat16)  # (1024,256) N,K
                data, _ = _mlc_quantize_q4_64(ow)
                sa, da = store_quantized_weight(self, data.tobytes())
                la["o_scale"].append(sa); la["o_data"].append(da)
            kw = kv_all[0, 0].transpose(-1, -2).contiguous().to(torch.bfloat16)  # (256,1024) N,K
            data, _ = _mlc_quantize_q4_64(kw)
            la["k_scale"], la["k_data"] = store_quantized_weight(self, data.tobytes())
            vw = kv_all[1, 0].transpose(-1, -2).contiguous().to(torch.bfloat16)
            data, _ = _mlc_quantize_q4_64(vw)
            la["v_scale"], la["v_data"] = store_quantized_weight(self, data.tobytes())

            # Gated MLP: gating_einsum (2, 1024, 4096) -> [gate_w, up_w], linear (4096, 1024)
            gating = _load("PaliGemma.llm.layers.mlp_1.gating_einsum")[layer]  # (2,1024,4096)
            gate_w = gating[0].transpose(-1, -2).contiguous().to(torch.bfloat16)  # (4096,1024) N,K
            data, _ = _mlc_quantize_q4_64(gate_w)
            la["mlp_gate_scale"], la["mlp_gate_data"] = store_quantized_weight(self, data.tobytes())
            up_w = gating[1].transpose(-1, -2).contiguous().to(torch.bfloat16)
            data, _ = _mlc_quantize_q4_64(up_w)
            la["mlp_up_scale"], la["mlp_up_data"] = store_quantized_weight(self, data.tobytes())
            la["mlp_down_scale"], la["mlp_down_data"] = \
                _store_matmul_layer("PaliGemma.llm.layers.mlp_1.linear", layer)

            self.ae_layer_addrs.append(la)

        # --- final AdaRMSNorm (applied after all 18 layers, before action_out_proj) ---
        self.ae_final_norm_dense_scale, self.ae_final_norm_dense_data = \
            _store_matmul("PaliGemma.llm.final_norm_1.Dense_0.kernel")
        self.ae_final_norm_dense_bias = _store_bf16("PaliGemma.llm.final_norm_1.Dense_0.bias")

        print(f"weight_init_action_expert done; params DRAM at 0x{self.get_params_dram_addr():X}")

    # ---- action-expert scratch tensors --------------------------------------
    def tensor_init_action_expert(self):
        """Allocate action-expert activation/attention scratch DRAM. Sizes use
        AE_ACTION_HORIZON_PADDED (S=64) for the suffix block and self.PREFIX_SEQ_LEN
        (P) for the cached prefix length -- see the ASSUMED KV-CACHE INTERFACE
        comment above compile_suffix_step for the P source."""
        bpe = 2
        H, I, D = self.AE_HIDDEN, self.AE_INTERMEDIATE, self.HEAD_DIM
        S = self.AE_ACTION_HORIZON_PADDED
        P = getattr(self, "PREFIX_SEQ_LEN", 1024)
        self.AE_PREFIX_SEQ_LEN = P
        Tkv = P + S
        self.AE_TKV = Tkv

        # Combined per-layer K/V (prefix rows [0:P] + this-step suffix rows [P:P+S]).
        # kv_heads=1 (MQA): single (Tkv, D) buffer per layer, reused across all 10
        # Euler steps (prefix rows copied once at init; suffix rows overwritten/step).
        self.AE_KV_LAYER_STRIDE = Tkv * D * bpe
        self.ae_k_combined = [self.allocate_tensor_dram(self.AE_KV_LAYER_STRIDE) for _ in range(self.AE_LAYERS)]
        self.ae_v_combined = [self.allocate_tensor_dram(self.AE_KV_LAYER_STRIDE) for _ in range(self.AE_LAYERS)]

        # Q buffer: (heads, Tkv, D) -- only rows [0:S] per head are real suffix
        # queries; rows [S:Tkv] are padding so prefill_flash_attention_core (which
        # assumes Q/K share the same seq_len) can run Q against the full Tkv K/V.
        # Only the first S output rows are read back.
        self.AE_Q_DRAM = self.allocate_tensor_dram(self.AE_HEADS * Tkv * D * bpe)
        self.AE_ATTN_OUT_DRAM = self.allocate_tensor_dram(self.AE_HEADS * Tkv * D * bpe)
        self.AE_ATTN_SCRATCH_DRAM = self.allocate_tensor_dram((D * Tkv + max(D, 64) * Tkv) * bpe)
        self.AE_ATTN_RESULT_DRAM = self.allocate_tensor_dram(S * H * bpe)  # un-headed (S,H) post-o-proj input
        self.AE_O_PROJ_DRAM = self.allocate_tensor_dram(S * H * bpe)

        # Shared-subroutine flash attention (same fix as compile_prefix): one flash
        # body compiled ONCE in compile_denoise_loop (after all 180 layer-step
        # bodies) and jumped to from every (step, layer, head) call site -- 1440
        # jumps into one body, instead of prefill_flash_attention_core statically
        # re-emitting a full Tkv~1088 attention body 180 times, which blew the
        # compiled denoise program up near the 4GB DRAM ceiling. K/V need per-layer
        # (not per-head) marshalling here since each layer has its own
        # ae_k_combined/ae_v_combined buffer (unlike prefix's one fixed buffer) --
        # copied into this fixed scratch once per (step,layer), reused for all 8
        # heads' jumps within that layer.
        self.AE_FLASH_Q_DRAM = self.allocate_tensor_dram(Tkv * D * bpe)
        self.AE_FLASH_K_DRAM = self.allocate_tensor_dram(Tkv * D * bpe)
        self.AE_FLASH_V_DRAM = self.allocate_tensor_dram(Tkv * D * bpe)
        self.AE_FLASH_OUT_DRAM = self.allocate_tensor_dram(Tkv * D * bpe)
        self.AE_FLASH_ATTN_P_DRAM = self.allocate_tensor_dram(Tkv * Tkv * bpe)

        # Suffix attention bias: (Tkv, Tkv) additive bf16, 0 for valid prefix+suffix
        # cols (bidirectional per pi0.5 ar_mask all-False), large-negative for the
        # [S:Tkv] padding columns/rows (unused rows are never read back, but the
        # columns feeding real rows' softmax must be masked so padding K/V garbage
        # doesn't pollute attention over rows [0:S]).
        NEG_INF = -1e9
        bias = torch.zeros(Tkv, Tkv, dtype=torch.bfloat16)
        bias[:, P + S:] = NEG_INF   # no such columns (P+S==Tkv) -- kept for clarity/symmetry
        bias[S:, :] = 0.0           # unused query rows; value irrelevant, never read back
        self.AE_BIAS_DRAM = self.get_params_dram_addr()
        self.dma_write(DMA_DEVICE_H2C, self.AE_BIAS_DRAM, bias.contiguous(), Tkv * Tkv * bpe)
        self.allocate_params_dram(Tkv * Tkv * bpe)

        # x / norm / adarms scratch (S, H)
        self.AE_X_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_NORM_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_ATTN_GATED_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_RESIDUAL_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_MLP_GATE_DRAM = self.allocate_tensor_dram(S * I * bpe)
        self.AE_MLP_UP_DRAM = self.allocate_tensor_dram(S * I * bpe)
        self.AE_MLP_MULT_DRAM = self.allocate_tensor_dram(S * I * bpe)
        self.AE_MLP_DOWN_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_MLP_GATED_DRAM = self.allocate_tensor_dram(S * H * bpe)

        # adarms conditioning scratch: modulation (1, 3*H), and its 3 broadcast-to-S copies
        self.AE_COND_DRAM = self.allocate_tensor_dram(1 * H * bpe)               # timestep embedding, (1,H)
        self.AE_MODULATION_DRAM = self.allocate_tensor_dram(1 * 3 * H * bpe)     # (1, 3H) = [scale,shift,gate]
        self.AE_SCALE_BCAST_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_SHIFT_BCAST_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_GATE_BCAST_DRAM = self.allocate_tensor_dram(S * H * bpe)

        # timestep embedding scratch (sincos -> time_mlp_in -> silu -> time_mlp_out -> silu)
        self.AE_SINCOS_DRAM = self.allocate_tensor_dram(1 * H * bpe)
        self.AE_TIME_HIDDEN_DRAM = self.allocate_tensor_dram(1 * H * bpe)

        # all-ones gamma constant: rms_norm_core multiplies by gamma directly (no
        # implicit +1, unlike gemma3's pre-offset convention), so AdaRMSNorm's
        # plain (no learned scale) RMSNorm needs gamma=1 rather than gamma=None
        # (rms_norm_core_dram_legacy dereferences GAMMA_DRAM_ADDR unconditionally).
        self.AE_ONES_DRAM = self.get_params_dram_addr()
        self.dma_write(DMA_DEVICE_H2C, self.AE_ONES_DRAM, torch.ones(H, dtype=torch.bfloat16).contiguous(), H * bpe)
        self.allocate_params_dram(H * bpe)

        # action tokens (x_t projected through action_in_proj) and the denoise state x_t (S, 32)
        self.AE_ACTION_TOK_DRAM = self.allocate_tensor_dram(S * H * bpe)
        self.AE_XT_DRAM = self.allocate_tensor_dram(S * self.AE_ACTION_DIM_PADDED * bpe)
        self.AE_VT_DRAM = self.allocate_tensor_dram(S * self.AE_ACTION_DIM_PADDED * bpe)
        # K-padded (32 -> 64) copy of x_t for the action_in_proj matmul (K must be
        # a multiple of UE_VECTOR_SIZE=64); zero-filled once, only cols [0:32] are
        # ever overwritten (cols [32:64] stay zero for the lifetime of the loop).
        self.AE_XT_PAD_DRAM = self.allocate_tensor_dram(S * 64 * bpe)
        zero_pad = torch.zeros(S, 64, dtype=torch.bfloat16)
        self.dma_write(DMA_DEVICE_H2C, self.AE_XT_PAD_DRAM, zero_pad.contiguous(), S * 64 * bpe)

        # Prefix KV cache placeholder, only used if the prefix agent hasn't wired
        # self.prefix_k/v_cache_addr yet (see ASSUMED PREFIX KV-CACHE INTERFACE).
        if not hasattr(self, "prefix_k_cache_addr"):
            print("[ae] WARNING: self.prefix_k_cache_addr not found -- allocating a "
                  "zero placeholder. Point this at the real prefix KV cache before "
                  "trusting suffix-attention numerics.")
            zero_row = torch.zeros(P, D, dtype=torch.bfloat16)
            self.prefix_k_cache_addr = []
            self.prefix_v_cache_addr = []
            for _ in range(self.AE_LAYERS):
                kaddr = self.get_params_dram_addr()
                self.dma_write(DMA_DEVICE_H2C, kaddr, zero_row.contiguous(), P * D * bpe)
                self.allocate_params_dram(P * D * bpe)
                vaddr = self.get_params_dram_addr()
                self.dma_write(DMA_DEVICE_H2C, vaddr, zero_row.contiguous(), P * D * bpe)
                self.allocate_params_dram(P * D * bpe)
                self.prefix_k_cache_addr.append(kaddr)
                self.prefix_v_cache_addr.append(vaddr)

        # Seed the combined K/V buffers' prefix rows [0:P] once (unchanged across
        # all 10 Euler steps / all layers' repeated suffix_step calls).
        for layer in range(self.AE_LAYERS):
            self.accelerator_memory_to_sram(self.prefix_k_cache_addr[layer], 0x00000, P * D)
            self.sram_to_accelerator_memory(0x00000, self.ae_k_combined[layer], P * D)
            self.accelerator_memory_to_sram(self.prefix_v_cache_addr[layer], 0x00000, P * D)
            self.sram_to_accelerator_memory(0x00000, self.ae_v_combined[layer], P * D)

        print(f"tensor_init_action_expert done; tensor DRAM at 0x{self.get_tensor_dram_addr():X}")

    # ---- small helpers --------------------------------------------------
    def _ae_broadcast_row(self, src_dram, dst_dram, rows, width):
        """Copy a single (1, width) bf16 row from src_dram to `rows` contiguous
        rows at dst_dram (broadcast across the row/batch dim -- used for AdaRMSNorm
        scale/shift/gate and the sincos/timestep conditioning vector)."""
        bpe = 2
        self.accelerator_memory_to_sram(src_dram, 0x00000, width)
        for r in range(rows):
            self.sram_to_accelerator_memory(0x00000, dst_dram + r * width * bpe, width)

    def _ae_matmul(self, M, K, N, A, scale_addr, data_addr, OUT, bias_addr=None, gpr_M_reg=None, **kw):
        """IF4 (q4_64) quantized matmul, per the quantization policy in
        weight_init_action_expert. Pass gpr_M_reg (primed with M via ADD_SET by
        the caller) to compile a compact PBI runtime loop instead of static-M
        unrolling -- required here because this body is itself repeated 180x
        (10 Euler steps x 18 layers); static-M was blowing the compiled program
        up to the point compilation didn't finish in 900s (see compile_prefix's
        identical fix for the root-cause writeup)."""
        self.matmat_mul_core(M=M, K=K, N=N, A_DRAM_ADDR=A, B_DRAM_ADDR=data_addr,
                              OUTPUT_DRAM_ADDR=OUT, is_B_quantized=True, data_type=TYPE.IF4,
                              SCALE_DRAM_ADDR=scale_addr, C_DRAM_ADDR=bias_addr, gpr_M_reg=gpr_M_reg, **kw)

    def _ae_ada_rms_norm(self, M, x_dram, dense_scale, dense_data, dense_bias,
                          norm_out_dram, gate_bcast_dram, apply_gate=True, gpr_M_reg=None):
        """AdaRMSNorm: plain RMSNorm (no gamma) on x, then a conditioning Dense
        (cond(1,1024) -> (1,3*1024)) split into scale/shift/gate, broadcast over
        the M suffix rows, applied as normed*(1+scale)+shift. Writes the gate
        broadcast to gate_bcast_dram for the caller to apply after attn/mlp.
        gpr_M_reg (primed with M) makes the RMSNorm's row loop a runtime PBI
        loop -- see _ae_matmul's docstring for why this matters here."""
        H = self.AE_HIDDEN
        bpe = 2
        # 1. RMSNorm (no gamma)
        self.rms_norm_core_dram(M=M, N=H, A_DRAM_ADDR=x_dram, OUTPUT_DRAM_ADDR=self.AE_NORM_DRAM,
                                 GAMMA_DRAM_ADDR=self.AE_ONES_DRAM, gpr_M_reg=gpr_M_reg)
        # 2. conditioning matmul: cond (1,H) @ dense (H,3H) -> modulation (1,3H), +bias
        # (M=1 here always -- one conditioning vector regardless of the caller's M -- so
        # no gpr_M_reg needed, a single-row matmul is already minimal.)
        self._ae_matmul(1, H, 3 * H, self.AE_COND_DRAM, dense_scale, dense_data,
                         self.AE_MODULATION_DRAM, bias_addr=dense_bias)
        # 3. split scale/shift/gate (each H wide) and broadcast each to M rows
        scale_addr = self.AE_MODULATION_DRAM
        shift_addr = self.AE_MODULATION_DRAM + H * bpe
        gate_addr = self.AE_MODULATION_DRAM + 2 * H * bpe
        self._ae_broadcast_row(scale_addr, self.AE_SCALE_BCAST_DRAM, M, H)
        self._ae_broadcast_row(shift_addr, self.AE_SHIFT_BCAST_DRAM, M, H)
        if apply_gate:
            self._ae_broadcast_row(gate_addr, gate_bcast_dram, M, H)
        # 4. (1 + scale) -- add 1.0 to the broadcast scale buffer in place
        self.accelerator_memory_to_sram(self.AE_SCALE_BCAST_DRAM, 0x00000, M * H)
        self.broadcast_add(scalar=1.0, sram_start_addr=0x00000, sram_wb_addr=0x00000, element_size=M * H)
        self.sram_to_accelerator_memory(0x00000, self.AE_SCALE_BCAST_DRAM, M * H)
        # 5. out = normed * (1+scale) + shift
        eltwise_mul_core_dram(self, size=M * H, A_DRAM_ADDR=self.AE_NORM_DRAM,
                               B_DRAM_ADDR=self.AE_SCALE_BCAST_DRAM, OUTPUT_DRAM_ADDR=norm_out_dram)
        eltwise_add_core_dram(self, size=M * H, A_DRAM_ADDR=norm_out_dram,
                               B_DRAM_ADDR=self.AE_SHIFT_BCAST_DRAM, OUTPUT_DRAM_ADDR=norm_out_dram)

    def _ae_gated_mlp(self, M, x_dram, la, out_dram, gpr_M_reg=None):
        """Gated MLP: gate=x@gate_w (gelu), up=x@up_w, out=(gate*up)@linear. Uses
        matmat_mul_core's gelu_enable fused activation on the gate branch, per the
        torch reference `F.gelu(x @ gate_w, approximate="none")`."""
        H, I = self.AE_HIDDEN, self.AE_INTERMEDIATE
        self._ae_matmul(M, H, I, x_dram, la["mlp_gate_scale"], la["mlp_gate_data"],
                         self.AE_MLP_GATE_DRAM, gelu_enable=True, gpr_M_reg=gpr_M_reg)
        self._ae_matmul(M, H, I, x_dram, la["mlp_up_scale"], la["mlp_up_data"], self.AE_MLP_UP_DRAM, gpr_M_reg=gpr_M_reg)
        eltwise_mul_core_dram(self, size=M * I, A_DRAM_ADDR=self.AE_MLP_GATE_DRAM,
                               B_DRAM_ADDR=self.AE_MLP_UP_DRAM, OUTPUT_DRAM_ADDR=self.AE_MLP_MULT_DRAM)
        self._ae_matmul(M, I, H, self.AE_MLP_MULT_DRAM, la["mlp_down_scale"], la["mlp_down_data"], out_dram, gpr_M_reg=gpr_M_reg)

    def _ae_sincos_time_embed(self, t_scalar):
        """Host-computed sincos timestep embedding (dim=AE_HIDDEN, matches
        sincos_pos_embed in pi05_torch_ref.py) DMA'd to AE_SINCOS_DRAM, then
        time_mlp_in -> silu -> time_mlp_out -> silu -> AE_COND_DRAM (the AdaRMSNorm
        conditioning vector for this Euler step)."""
        H = self.AE_HIDDEN
        min_period, max_period = 4e-3, 4.0
        frac = torch.linspace(0.0, 1.0, H // 2)
        period = min_period * (max_period / min_period) ** frac
        sinusoid = t_scalar * (1.0 / period) * 2 * math.pi
        emb = torch.cat([torch.sin(sinusoid), torch.cos(sinusoid)]).to(torch.bfloat16)
        self.dma_write(DMA_DEVICE_H2C, self.AE_SINCOS_DRAM, emb.contiguous(), H * 2)

        self._ae_matmul(1, H, H, self.AE_SINCOS_DRAM, self.ae_time_in_scale, self.ae_time_in_data,
                         self.AE_TIME_HIDDEN_DRAM, bias_addr=self.ae_time_in_bias, silu_enable=True)
        self._ae_matmul(1, H, H, self.AE_TIME_HIDDEN_DRAM, self.ae_time_out_scale, self.ae_time_out_data,
                         self.AE_COND_DRAM, bias_addr=self.ae_time_out_bias, silu_enable=True)

    # ---- one action-expert transformer layer (attention + gated MLP) --------
    def compile_suffix_step(self, layer_idx, x_in_dram, x_out_dram, gpr_M_reg=None, flash_ctx=None):
        """One action-expert layer body: AdaRMSNorm -> MQA attention (suffix Q vs
        combined prefix+suffix K/V) -> gated residual -> AdaRMSNorm -> gated MLP
        -> gated residual. Mirrors suffix_step()'s per-layer loop body in
        pi05_torch_ref.py (the `suf_tokens is not None` branch of joint_attention).
        gpr_M_reg (primed with S by the caller) makes every M=S matmul/RMSNorm in
        this body a compact PBI runtime loop -- this body is itself repeated 180x
        (10 Euler steps x 18 layers), so static-M unrolling blew the compiled
        program up past the point compilation could finish in any reasonable time.
        flash_ctx (dict from compile_denoise_loop): {prog_base, gpr_bucket, gpr_ret,
        call_sites} -- shared across all 180 calls; the flash body itself is
        compiled ONCE by the caller after every call site has been emitted."""
        la = self.ae_layer_addrs[layer_idx]
        H, D = self.AE_HIDDEN, self.HEAD_DIM
        S = self.AE_ACTION_HORIZON_PADDED
        Tkv, P = self.AE_TKV, self.AE_PREFIX_SEQ_LEN
        k_combined = self.ae_k_combined[layer_idx]
        v_combined = self.ae_v_combined[layer_idx]

        # 1. AdaRMSNorm (attention conditioning)
        self._ae_ada_rms_norm(S, x_in_dram, la["pre_attn_norm_dense_scale"], la["pre_attn_norm_dense_data"],
                               la["pre_attn_norm_dense_bias"], self.AE_NORM_DRAM, self.AE_GATE_BCAST_DRAM,
                               gpr_M_reg=gpr_M_reg)

        # 2. K/V projection for the suffix rows only -> combined buffer rows [P:P+S]
        self._ae_matmul(S, H, D, self.AE_NORM_DRAM, la["k_scale"], la["k_data"],
                         k_combined + P * D * 2, gpr_M_reg=gpr_M_reg)
        self._ae_matmul(S, H, D, self.AE_NORM_DRAM, la["v_scale"], la["v_data"],
                         v_combined + P * D * 2, gpr_M_reg=gpr_M_reg)

        # 3. Per-head Q projection into the (heads, Tkv, D) padded Q buffer (rows
        #    [0:S] real, [S:Tkv] unused/garbage -- see tensor_init_action_expert).
        head_bytes = Tkv * D * 2
        for h in range(self.AE_HEADS):
            self._ae_matmul(S, H, D, self.AE_NORM_DRAM, la["q_scale"][h], la["q_data"][h],
                             self.AE_Q_DRAM + h * head_bytes, gpr_M_reg=gpr_M_reg)

        # 4. MQA flash attention: Q (heads, Tkv, D) vs shared K/V (Tkv, D), additive
        #    bias (Tkv, Tkv). Only rows [0:S] of the output are meaningful.
        #    Per head: copy this layer's K/V (same for all 8 heads) + this head's
        #    Q into the fixed AE_FLASH_* scratch, jump into the shared subroutine,
        #    copy the result out to this head's slot in AE_ATTN_OUT_DRAM.
        self._dram_copy(Tkv * D * 2, k_combined, self.AE_FLASH_K_DRAM)
        self._dram_copy(Tkv * D * 2, v_combined, self.AE_FLASH_V_DRAM)
        for h in range(self.AE_HEADS):
            self._dram_copy(head_bytes, self.AE_Q_DRAM + h * head_bytes, self.AE_FLASH_Q_DRAM)
            self.generate_instruction_add_set(flash_ctx["gpr_bucket"], flash_ctx["num_buckets"])
            self.pad_capture_to_64b_boundary()
            return_word_addr = ue_35bit_addr_shifter(
                flash_ctx["prog_base"] + (self.capture_count + 2) * INSTRUCTION_SIZE_BYTES)
            self.generate_instruction_add_set(flash_ctx["gpr_ret"], return_word_addr)
            flash_ctx["call_sites"].append(self.capture_count)
            self.generate_instruction_jump_abs(target_instruction_word_addr=0)
            self._dram_copy(head_bytes, self.AE_FLASH_OUT_DRAM, self.AE_ATTN_OUT_DRAM + h * head_bytes)

        # 5. un-stack heads' first S rows -> (S, heads*D) token-major, o-proj
        for h in range(self.AE_HEADS):
            self.accelerator_memory_to_sram(self.AE_ATTN_OUT_DRAM + h * head_bytes, 0x00000, S * D)
            self.sram_to_accelerator_memory(0x00000, self.AE_ATTN_RESULT_DRAM, S * D,
                                             stride_bytes_per_chunk=D * 2, stride_jump_bytes=H * 2)
        # o projection is per-head (256,1024) -> accumulate into AE_O_PROJ_DRAM
        # via C_DRAM_ADDR-chained adds (first head writes, rest accumulate).
        for h in range(self.AE_HEADS):
            head_slice = self.AE_ATTN_RESULT_DRAM + h * D * 2
            self._ae_matmul(S, D, H, head_slice, la["o_scale"][h], la["o_data"][h],
                             self.AE_O_PROJ_DRAM, bias_addr=(self.AE_O_PROJ_DRAM if h > 0 else None),
                             gpr_M_reg=gpr_M_reg)

        # 6. gated residual: x = x + gate * attn_out
        eltwise_mul_core_dram(self, size=S * H, A_DRAM_ADDR=self.AE_O_PROJ_DRAM,
                               B_DRAM_ADDR=self.AE_GATE_BCAST_DRAM, OUTPUT_DRAM_ADDR=self.AE_ATTN_GATED_DRAM)
        eltwise_add_core_dram(self, size=S * H, A_DRAM_ADDR=x_in_dram,
                               B_DRAM_ADDR=self.AE_ATTN_GATED_DRAM, OUTPUT_DRAM_ADDR=self.AE_RESIDUAL_DRAM)

        # 7. AdaRMSNorm (mlp conditioning)
        self._ae_ada_rms_norm(S, self.AE_RESIDUAL_DRAM, la["pre_ffw_norm_dense_scale"],
                               la["pre_ffw_norm_dense_data"], la["pre_ffw_norm_dense_bias"],
                               self.AE_NORM_DRAM, self.AE_GATE_BCAST_DRAM, gpr_M_reg=gpr_M_reg)

        # 8. gated MLP + gated residual
        self._ae_gated_mlp(S, self.AE_NORM_DRAM, la, self.AE_MLP_DOWN_DRAM, gpr_M_reg=gpr_M_reg)
        eltwise_mul_core_dram(self, size=S * H, A_DRAM_ADDR=self.AE_MLP_DOWN_DRAM,
                               B_DRAM_ADDR=self.AE_GATE_BCAST_DRAM, OUTPUT_DRAM_ADDR=self.AE_MLP_GATED_DRAM)
        eltwise_add_core_dram(self, size=S * H, A_DRAM_ADDR=self.AE_RESIDUAL_DRAM,
                               B_DRAM_ADDR=self.AE_MLP_GATED_DRAM, OUTPUT_DRAM_ADDR=x_out_dram)

    # ---- full flow-matching denoising loop -----------------------------------
    def compile_denoise_loop(self):
        """10-step Euler integration (dt = -1/10, t: 1.0 -> 0.0), each step running
        action_in_proj -> timestep embed -> 18 action-expert layers -> final
        AdaRMSNorm -> action_out_proj -> x_t += dt * v_t. Mirrors the loop body in
        run_pi05() (pi05_torch_ref.py).

        Fully unrolled (10 steps x 18 layers = 180 static layer bodies) at the
        Euler-step level -- the per-step work (host-computed timestep embedding,
        weight addresses) is compile-time constant, so unrolling the OUTER loop is
        simplest for first bring-up. BUT every one of those 180 layer bodies'
        matmuls/RMSNorms now runs through a PBI runtime M-loop (gpr_M_reg, primed
        once below) instead of static-M row unrolling -- without this, compiling
        180 fully-unrolled layer bodies didn't finish in 900s (same root cause as
        compile_prefix's original 684MB blowup, compounded ~10x by the outer
        unroll). This is the fix, not a loop_start/loop_end construct around the
        Euler steps themselves (that's a further possible optimization, not
        required to get this compiling in reasonable time).

        Assumes self.AE_XT_DRAM already holds the initial noise sample (S, 32) --
        caller (run harness) DMAs it in before invoking compile_denoise_loop(), or
        it defaults to whatever tensor_init_action_expert() left there (uninitialized).
        """
        S, H = self.AE_ACTION_HORIZON_PADDED, self.AE_HIDDEN
        dt = -1.0 / self.AE_NUM_DENOISE_STEPS
        t = 1.0

        ae_S_reg = self.alloc_isa_reg()
        self.generate_instruction_add_set(ae_S_reg, S)

        # Shared-subroutine flash attention context, threaded into every
        # compile_suffix_step call across all 10 steps x 18 layers; the actual
        # subroutine body is compiled once, after the full loop below, and every
        # accumulated call site gets its jump patched to it (see compile_suffix_step
        # and tensor_init_action_expert's AE_FLASH_* buffers for the full rationale).
        Tkv = self.AE_TKV
        flash_ctx = {
            "prog_base": self.get_program_dram_addr(),
            "gpr_bucket": self.alloc_isa_reg(),
            "gpr_ret": self.alloc_isa_reg(),
            "call_sites": [],
            "num_buckets": Tkv // UE_VECTOR_SIZE,
        }

        for step in range(self.AE_NUM_DENOISE_STEPS):
            # action_in_proj: x_t (S,32) -> action_tokens (S,H). K must be a
            # multiple of 64 (matmat_mul_core/IF4 block_size), so x_t is copied
            # into the K-padded (S,64) scratch buffer's first 32 cols first.
            self.accelerator_memory_to_sram(self.AE_XT_DRAM, 0x00000, S * self.AE_ACTION_DIM_PADDED)
            self.sram_to_accelerator_memory(0x00000, self.AE_XT_PAD_DRAM, S * self.AE_ACTION_DIM_PADDED,
                                             stride_bytes_per_chunk=self.AE_ACTION_DIM_PADDED * 2,
                                             stride_jump_bytes=64 * 2)
            self._ae_matmul(S, 64, H, self.AE_XT_PAD_DRAM,
                             self.ae_action_in_scale, self.ae_action_in_data,
                             self.AE_ACTION_TOK_DRAM, bias_addr=self.ae_action_in_bias, gpr_M_reg=ae_S_reg)

            # timestep embedding -> AE_COND_DRAM (this step's AdaRMSNorm conditioning)
            self._ae_sincos_time_embed(t)

            # 18 action-expert layers
            x_cur = self.AE_ACTION_TOK_DRAM
            for layer_idx in range(self.AE_LAYERS):
                x_next = self.AE_X_DRAM if x_cur is not self.AE_X_DRAM else self.AE_ACTION_TOK_DRAM
                self.compile_suffix_step(layer_idx, x_cur, x_next, gpr_M_reg=ae_S_reg, flash_ctx=flash_ctx)
                x_cur = x_next

            # final AdaRMSNorm (no gate applied -- action_out_proj consumes the
            # normed output directly, per the real bug noted in pi05_torch_ref.py)
            self._ae_ada_rms_norm(S, x_cur, self.ae_final_norm_dense_scale,
                                   self.ae_final_norm_dense_data, self.ae_final_norm_dense_bias,
                                   self.AE_NORM_DRAM, self.AE_GATE_BCAST_DRAM, apply_gate=False,
                                   gpr_M_reg=ae_S_reg)

            # action_out_proj: (S,H) -> v_t (S,32)
            self._ae_matmul(S, H, self.AE_ACTION_DIM_PADDED, self.AE_NORM_DRAM,
                             self.ae_action_out_scale, self.ae_action_out_data,
                             self.AE_VT_DRAM, bias_addr=self.ae_action_out_bias, gpr_M_reg=ae_S_reg)

            # Euler step: x_t = x_t + dt * v_t
            self.accelerator_memory_to_sram(self.AE_VT_DRAM, 0x00000, S * self.AE_ACTION_DIM_PADDED)
            self.broadcast_mul(scalar=dt, sram_start_addr=0x00000, sram_wb_addr=0x00000,
                                element_size=S * self.AE_ACTION_DIM_PADDED)
            self.sram_to_accelerator_memory(0x00000, self.AE_VT_DRAM, S * self.AE_ACTION_DIM_PADDED)
            eltwise_add_core_dram(self, size=S * self.AE_ACTION_DIM_PADDED, A_DRAM_ADDR=self.AE_XT_DRAM,
                                   B_DRAM_ADDR=self.AE_VT_DRAM, OUTPUT_DRAM_ADDR=self.AE_XT_DRAM)
            t += dt

        # Main per-(step,layer) program ends here; the shared flash-attention
        # subroutine (jumped to from every per-head call site inside
        # compile_suffix_step, 1440 sites total) is compiled once below.
        self.generate_instruction_halt()

        ae_sub_start, _ae_flops = self.flash_attention_core(
            head_dim=self.HEAD_DIM, seq_len=Tkv,
            Q_DRAM_ADDR=self.AE_FLASH_Q_DRAM, K_DRAM_ADDR=self.AE_FLASH_K_DRAM,
            V_DRAM_ADDR=self.AE_FLASH_V_DRAM, OUTPUT_DRAM_ADDR=self.AE_FLASH_OUT_DRAM,
            SCRATCH_DRAM_ADDR=self.AE_ATTN_SCRATCH_DRAM, ATTN_P_DRAM_ADDR=self.AE_FLASH_ATTN_P_DRAM,
            IDENTITY_DRAM_ADDR=self.identity_addr, BIAS_DRAM_ADDR=self.AE_BIAS_DRAM,
            gpr_bucket_idx=flash_ctx["gpr_bucket"], num_buckets=flash_ctx["num_buckets"],
            gpr_ret_id=flash_ctx["gpr_ret"])
        for _idx in flash_ctx["call_sites"]:
            self._patch_jump_immediate(_idx, ue_35bit_addr_shifter(ae_sub_start))

        self.release_isa_reg()  # flash_ctx["gpr_ret"]
        self.release_isa_reg()  # flash_ctx["gpr_bucket"]
        self.release_isa_reg()  # ae_S_reg
        print("compile_denoise_loop done: 10-step Euler action-expert flow-matching stack compiled")

    # =========================================================================
    # End-to-end driver: real sample images -> vision (x3) -> prefix -> denoise
    # loop -> readback. Integration pass reconciling the vision/prefix/action-
    # expert stacks written independently above.
    # =========================================================================
    def _patchify(self, image_hwc):
        """image_hwc: (224,224,3) float32 in [-1,1] -> (256, 588) float32, matching
        pi05_torch_ref.vision_encode's unfold+reshape (patch_size=14, 16x16 patches)."""
        ps, n_side = 14, 16
        x = image_hwc.reshape(n_side, ps, n_side, ps, 3)
        x = x.transpose(0, 2, 1, 3, 4).reshape(n_side * n_side, ps * ps * 3)
        return x

    def run_vision(self, images_hwc):
        """images_hwc: list of 3 (224,224,3) float32 numpy arrays in [-1,1].
        Runs compile_encoder() once per image slot, returns (3*256, 2048) bf16
        tensor of concatenated vision tokens (host-side, read back via DMA)."""
        HO = self.VIS_HEAD_OUT
        S = self.VIS_S
        PK = self.VIS_PATCH_K
        outs = []
        for i, img in enumerate(images_hwc):
            patches = self._patchify(img)  # (256, 588)
            patches_pad = np.zeros((S, PK), dtype=np.float32)
            patches_pad[:, :patches.shape[1]] = patches
            pixel_t = torch.from_numpy(patches_pad).to(torch.bfloat16)
            self.dma_write(DMA_DEVICE_H2C, self.VIS_PIXEL_IN_DRAM, pixel_t, S * PK * 2)

            prog_addr = self.compile_encoder()
            self.start_execute_from_dram(prog_addr)
            self._wait_with_heartbeat(f"vision slot {i}", timeout=180.0)

            buf = bytearray(S * HO * 2)
            self.dma_read(DMA_DEVICE_C2H, self.VIS_HEAD_OUT_DRAM, buf, len(buf))
            out = torch.frombuffer(bytes(buf), dtype=torch.bfloat16).reshape(S, HO).clone()
            outs.append(out)
            print(f"  [vision] slot {i} done")
        return torch.cat(outs, dim=0)  # (3*256, 2048)

    def run_inference(self, images_hwc, prompt_tokens, noise32=None):
        """Full forward pass on real hardware. images_hwc: list of 3 (224,224,3)
        float32 arrays in [-1,1]. prompt_tokens: 1-D list/array of token ids.
        Returns (10,32) numpy action array (caller slices [:, :7])."""
        t0 = time.perf_counter()
        vision_tokens = self.run_vision(images_hwc)
        t_vision = time.perf_counter() - t0

        t1 = time.perf_counter()
        seq_len = _CFG["model"]["prefill_max_seq_len"]
        valid_len = self.embed_and_concat_prefix(prompt_tokens, vision_tokens, seq_len=seq_len)
        prog_addr = self._compile_and_run(lambda: self.compile_prefix(seq_len, valid_len), label="prefix")
        t_prefix = time.perf_counter() - t1

        t2 = time.perf_counter()
        self.tensor_init_action_expert()
        S, AD = self.AE_ACTION_HORIZON_PADDED, self.AE_ACTION_DIM_PADDED
        if noise32 is None:
            noise32 = np.zeros((S, AD), dtype=np.float32)
            noise32[:10, :7] = np.random.RandomState(0).randn(10, 7)
        self.dma_write(DMA_DEVICE_H2C, self.AE_XT_DRAM,
                        torch.from_numpy(noise32).to(torch.bfloat16), S * AD * 2)
        self._compile_and_run(self.compile_denoise_loop, label="denoise_loop")
        t_denoise = time.perf_counter() - t2

        buf = bytearray(S * AD * 2)
        self.dma_read(DMA_DEVICE_C2H, self.AE_XT_DRAM, buf, len(buf))
        out = torch.frombuffer(bytes(buf), dtype=torch.bfloat16).reshape(S, AD).float().numpy()
        actions = out[:10, :7]

        print(f"timing: vision={t_vision:.2f}s prefix={t_prefix:.2f}s denoise={t_denoise:.2f}s "
              f"total={t_vision+t_prefix+t_denoise:.2f}s")
        return actions

    # XDMA driver has a per-os.write() transfer size limit (~16-64MB, matching
    # parakeet_test.py's/mobilenetv2_224_test.py's documented workaround). A
    # single-shot dma_write of a large program blob (pi05's compiled prefix
    # program is ~684MB) fails deterministically with `[Errno 512]` after
    # transferring a partial chunk (~57MB observed) -- this was misread at
    # first as an address-boundary bug (it correlated with >4GB addresses by
    # coincidence: the small 745KB vision program always fit under the limit,
    # while the ~684MB prefix program never does, regardless of address).
    # Real fix: chunk large writes, exactly like parakeet/mobilenetv2 already do.
    DMA_CHUNK_BYTES = 1 * 1024 * 1024  # 1 MB per chunk

    def _dma_write_retry(self, device, address, buffer, size, attempts=5):
        """Chunked + retried DMA write. A failed/incomplete program-blob write
        here means start_execute_from_dram runs stale/garbage DRAM content --
        this bit us for real (denoise-loop program silently didn't get written,
        producing garbage action output) so this is NOT optional."""
        data = bytes(buffer[:size]) if isinstance(buffer, (bytes, bytearray)) else buffer
        if size <= self.DMA_CHUNK_BYTES:
            for i in range(attempts):
                n = self.dma_write(device, address, data, size)
                if n == size:
                    return n
                print(f"  [dma_write_retry] attempt {i+1}/{attempts} failed (wrote {n}, wanted {size}), retrying...")
            raise RuntimeError(f"dma_write to 0x{address:X} failed after {attempts} attempts")

        offset = 0
        while offset < size:
            chunk_size = min(self.DMA_CHUNK_BYTES, size - offset)
            chunk = data[offset:offset + chunk_size] if isinstance(data, (bytes, bytearray)) \
                else data.flatten()[offset:offset + chunk_size]
            self._dma_write_retry(device, address + offset, chunk, chunk_size, attempts=attempts)
            offset += chunk_size
        return size

    def _wait_with_heartbeat(self, label, timeout=180.0, heartbeat_every=10.0):
        """wait_queue wrapper that prints elapsed seconds every heartbeat_every
        seconds on a background thread, so a real hang (dead silent, no CPU
        activity) is visually distinguishable from a slow-but-alive execute --
        we were guessing this blind before and burning time on ambiguous kills."""
        import threading
        t0 = time.perf_counter()
        stop = threading.Event()
        def _hb():
            while not stop.wait(heartbeat_every):
                print(f"  [{label}] ... still waiting on FPGA queue ({time.perf_counter()-t0:.0f}s elapsed)", flush=True)
        hb_th = threading.Thread(target=_hb, daemon=True)
        hb_th.start()
        try:
            self.wait_queue(timeout)
        finally:
            stop.set()
            hb_th.join(timeout=1.0)
        print(f"  [{label}] done in {time.perf_counter()-t0:.1f}s", flush=True)

    def _compile_and_run(self, compile_fn, label="compile_and_run"):
        """compile_fn must itself do start_capture/.../stop_capture + DMA the
        program bytes and return the program addr (compile_prefix/compile_denoise_loop
        don't currently do the capture/dma/execute bookkeeping compile_encoder does --
        wrap them the same way here)."""
        self.start_capture()
        prog_addr = compile_fn()
        # compile_prefix/compile_denoise_loop don't call stop_capture/emit themselves
        # (only compile_encoder does) -- if compile_fn already stopped capture and
        # returned an addr (compile_encoder-style), reuse it; else emit now.
        if self.capture_buffer:
            all_bytes = bytearray()
            for inst in self.capture_buffer:
                all_bytes.extend(inst.get_bytes())
            prog_addr = self.get_program_dram_addr()
            self._dma_write_retry(DMA_DEVICE_H2C, prog_addr, all_bytes, len(all_bytes))
            self.allocate_program_dram(len(all_bytes))
            self.clear_capture_buffer()
        self.stop_capture()
        self.start_execute_from_dram(prog_addr)
        self._wait_with_heartbeat(label, timeout=180.0)
        return prog_addr


def main():
    import time as _time
    ue = Pi05Libero_UnifiedEngine()
    init_hang_prevention(ue)
    ue.weight_init()
    ue.tensor_init(_CFG["defaults"].get("max_seq", 512))

    sample_dir = Path.home() / "apex-compute-ML" / "simple-llm" / "src" / "models" / "pi0_5" / "sample_data"
    img = np.load(sample_dir / "sample_0_image.npy").astype(np.float32) / 127.5 - 1.0
    wrist = np.load(sample_dir / "sample_0_wrist_image.npy").astype(np.float32) / 127.5 - 1.0
    pad = np.zeros_like(img)
    # resize 256->224 (host-side, matches pi05_torch_ref.py)
    import torch.nn.functional as _F
    def _resize(a):
        t = torch.from_numpy(a).permute(2, 0, 1).unsqueeze(0).float()
        t = _F.interpolate(t, size=(224, 224), mode="bilinear", align_corners=False)
        return t.squeeze(0).permute(1, 2, 0).numpy()
    images = [_resize(img), _resize(wrist), _resize(pad)]

    prompt_tokens = np.random.RandomState(1).randint(0, 257152, size=(16,))

    actions = ue.run_inference(images, prompt_tokens)
    np.set_printoptions(precision=4, suppress=True)
    print("action_chunk shape:", actions.shape)
    print(actions)


if __name__ == "__main__":
    main()
